### ISSUE TITLE
Error when validating token  

### ISSUE THREAD

**Issue by Arlus** [google/google-api-python-client#103]
I'm using Python 3.4 and Django 1.8

When I try to validate the token in my view as follows:
`if not xsrfutil.validate_token(settings.SECRET_KEY, request.GET['state'], user):`

i get an error:
`String object without encoding`

**Comment by initialkommit** [comment]
Do you still have that problem? I also need a solution.

**Comment by MhSaadany** [comment]
There is a solution in https://github.com/google/google-api-python-client/issues/58.

**Comment by bantini** [comment]
Closing this because of the workaround for 58, and there are no complaints with the latest version of the library.
