### ISSUE TITLE
Discussion: discovery doc caching

### ISSUE THREAD

**Issue by tmatsuo** [google/google-api-python-client#110]
discovery.build() is handy, but afaik, it should be avoided in any production systems, especially if the API is considered stable and you should cache the discovery document and re-use it.

When Cloud Pub/Sub released the API version v1, I started to cache ([appengine](https://github.com/GoogleCloudPlatform/cloud-pubsub-samples-python/blob/5ea5c39f74e7644feeff2d5e81df5b9549ce3c6b/appengine-push/discovery_doc.py)/[other](https://github.com/GoogleCloudPlatform/cloud-pubsub-samples-python/blob/5ea5c39f74e7644feeff2d5e81df5b9549ce3c6b/cmdline-pull/discovery_doc.py)) the discovery document in our samples.

It is great if there is a library, or even discovery.build() takes care of all the caching stuff under the cover, so I will start working on either of 1) create an independent library that does caching, or 2) create a PR to google-api-python-client.

Before I proceed, I'd like to ask: Which do you guys prefer?

**Comment by tmatsuo** [comment]
Ping @nathanielmanistaatgoogle 
WDYT?

**Comment by nathanielmanistaatgoogle** [comment]
I'm open to a pull request in this project. Would the public API change at all? Would clients have to behave differently? What are the ways the new behavior could be accidentally misused, and what would the consequences be?

**Comment by tmatsuo** [comment]
There shouldn't be any API changes. All the caching should be done just under the cover.
