### ISSUE TITLE
[Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-3065.write-test'

### ISSUE THREAD

**Issue by jwdinkel** [google/google-api-python-client#116]
Hello,

Can anybody help me with this procedure?

**Create a new Google Compute Engine:**
gcloud compute instances create datastore-test --zone europe-west1-b --scopes compute-rw,datastore,userinfo-email

**Use the [web console](https://console.developers.google.com)**
Open the instance using "Open in browser window".

**Run this command:**
easy_install --upgrade google-api-python-client

**Results with Error:**
error: can't create or remove files in install directory
The following error occurred while trying to add or remove files in the
installation directory:
    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-3065.write-test'
The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:
    /usr/local/lib/python2.7/dist-packages/
Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.
For information on other options, you may wish to consult the
documentation at:
  https://pythonhosted.org/setuptools/easy_install.html
Please make the appropriate changes for your system and try again.

**Comment by tmatsuo** [comment]
I think you may want to use sudo as follows:

`sudo easy_install --upgrade google-api-python-client`

or use pip and create a virtualenv so that you can install packages as a normal user.

**Comment by Jagdeepkumarboyat** [comment]
sudo python setup.py install

**Comment by AbebeGetnet** [comment]
After 'sudo python setup.py install', Where to get the build package to run?

**Comment by liangDYL** [comment]
I have meet the same problem, and I have resolved it by uinsg python setup.py install --user, you can try it.
