### ISSUE TITLE
When Video Uploads Fail Files are Still Processed

### ISSUE THREAD

**Issue by ghost** [google/google-api-python-client#122]
I was asked to reference this issue here: tokland/youtube-upload/issues/54

When uploading a video using the tool youtube-upload, if the end of file was unexpectedly reached or my network cut out YouTube still processed and published what it received. I think it would be nice to have a mechanism to address this possibility.

**Comment by tseaver** [comment]
The current [Python api-samples example for uploading video](https://github.com/youtube/api-samples/blob/master/python/upload_video.py) uses the "resumable upload" version of the API, which allows an interrupted upload to be completed after backoff.
