### ISSUE TITLE
"Issue tracker" link is broken on https://google.github.io/google-api-python-client/contributing.html

### ISSUE THREAD

**Issue by harisibrahimkv** [google/google-api-python-client#126]
The "issue tracker" link points to https://github.com/google/google/google-api-python-client/issues

It should point to https://github.com/google/google-api-python-client/issues

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the report! Now that I spend a while looking at it... something's wrong with google-api-python-client's documentation process; I've elaborated a bit in #75. In the meantime perhaps contribute a pull request against our `gh-pages` branch?

**Comment by pferate** [comment]
Created PR #143 to resolve this.

**Comment by bantini** [comment]
Closing because this issue has been resolved.
