### ISSUE TITLE
NameError: name 'serviceName' is not defined

### ISSUE THREAD

**Issue by ilius** [google/google-api-python-client#130]
File "oauth2client/oauth2client/util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "google-api-python-client/googleapiclient/discovery.py", line 193, in build
    content = _retrieve_discovery_doc(requested_url, http, cache_discovery, cache)
  File "googleapiclient/discovery.py", line 236, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName,
NameError: name 'serviceName' is not defined

The same for `version` too, not passed to this function
Other http errors are also not handled.
I suggest you move out the codes inside function `_retrieve_discovery_doc`, and remove this function because it's only used once.
The code is messy

**Comment by nathanielmanistaatgoogle** [comment]
@tmatsuo, what do you make of this?

**Comment by tmatsuo** [comment]
@ilius Now the fix is in. Thanks for the report!

> The code is messy

I kinda agree, but it's messy because the intention of the new code is automagically setting up the cache for you. I'm open to any suggestions to improve the code though.

Thanks again :)

**Comment by ilius** [comment]
Your welcome :)
I hope I can help developing this project soon
