### ISSUE TITLE
"Invalid request: Start time is too old." would be much better than the confusing and incorrect "Invalid request: Start time is after end time."

### ISSUE THREAD

**Issue by carlopires** [google/google-api-python-client#148]
Some APIs calls, like [Reports activities.list](https://developers.google.com/admin-sdk/reports/v1/reference/activities/list) requires that `endDate` goes after `startDate`. This kind of call should be supported by this module.

**Comment by nathanielmanistaatgoogle** [comment]
Please add more detail - how does this library look today without such support, and how would this library look in the future with such support?

**Comment by carlopires** [comment]
Look at this traceback:

    Traceback (most recent call last):
      File "/home/ubuntu/test.py", line 418, in api_call
        return activities_service.list(**kwargs).execute()
      File "/usr/local/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
        return wrapped(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/googleapiclient/http.py", line 729, in execute
        raise HttpError(resp, content, uri=self.uri)
    HttpError: <HttpError 400 when requesting https://www.googleapis.com/admin/reports/v1/activity/users/all/applications/login?alt=json&endTime=2015-04-18T23%3A48%3A47Z&startTime=2015-04-17T23%3A48%3A47Z returned "Invalid request: Start time is after end time.">

It's clear that startDate is not after endDate, therefore, this error led me to believe that the error was occurring due to the position of dates arguments in the URI request.

I managed to test the API call changing the position of arguments but I've had the same error.

After many tests, I found out that the error may happen when startDate is older than ~120 days. The error message caused the confusion. May be the Google API engineers should change the message to make it to help the user to understand what is really causing the error.

You can close the issue. Thanks.

**Comment by nathanielmanistaatgoogle** [comment]
Thank you for the follow-up. It sounds like there's a chance here to better serve our users, but it would be a change to the behavior of Google's servers rather than here in the `google-api-python-client` library. Is that correct? Or have I misread what you've written, and the world is as perfect as it can be?

**Comment by carlopires** [comment]
This is a chance to fix the message returned by Google backend servers. "Invalid request: Start time is too old." should be much better than the confuse "Invalid request: Start time is after end time.".

**Comment by nathanielmanistaatgoogle** [comment]
Thanks much. I've filed a Google-internal report about this and will try to push it to resolution.

**Comment by nathanielmanistaatgoogle** [comment]
Good news: a change has been made improving the error message.

Bad news: it will take about a month to percolate through our systems and be visible externally.

Please let me know here in this issue if the problem of the unhelpful error message still appears after 1 December 2015.
