### ISSUE TITLE
400 error when (resumable) uploading files of size > 20 MB

### ISSUE THREAD

**Issue by sr-murthy** [google/google-api-python-client#153]
I'm writing an upload script that uploads CSV files to a Google Drive folder using resumable uploads - am using this as a reference

https://developers.google.com/api-client-library/python/guide/media_upload

See the code below.

It seems to work file for files of size <= 20MB, but bigger files are causing problems.

I've got a 43 MB CSV file which I am trying to upload using a chunk size of 5 MiB but am getting a 400 error on the last chunk upload:

```
file_meta = {'title': 'test.csv', 'description': 'Test CSV', 'mimeType': 'text/csv', 'parents': [{'id': myfolder_key}]}
convert_to_Google_Sheets = True
chunk_size = 1024*1024*5
content = <MediaIoBaseUpload object, resumable, 5 MiB chunk size>
req = drive.files().insert(body=file_meta, media_body=content, convert=convert_to_Google_Sheets)
response is None
while not response:
  status, response = req.next_chunk()
  if status:
    print "Uploaded %d%%." % int(status.progress() * 100)
```

The upload seems to progress fine until we get to the last chunk, when it terminates with a 400 error:

```
Uploaded 11%.
Uploaded 23%.
Uploaded 34%.
Uploaded 46%.
Uploaded 57%.
Uploaded 69%.
Uploaded 81%.
Uploaded 92%.
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/usr/local/lib/python2.6/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/googleapiclient/http.py", line 880, in next_chunk
    return self._process_response(resp, content)
  File "/usr/local/lib/python2.6/dist-packages/googleapiclient/http.py", line 907, in _process_response
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 400 when requesting https://www.googleapis.com/upload/drive/v2/files?uploadType=resumable&convert=true&alt=json returned "Bad Request">
```

**Comment by JohnGale87** [comment]
Did you ever mange to solve this issue? I'm getting the same thing.

**Comment by sr-murthy** [comment]
Oh god, this was a long time ago. I'm not able to recall 100% but I think it was that `convert=convert_to_Google_Sheets` argument, i.e. had to remove it.

**Comment by JohnGale87** [comment]
For anybody else reviewing this I can confirm that it was the convert flag. Conversion is still possible, but you need to do something like this...


convert = True
original_mimetype = 'text/csv'
body_mimetype = 'application/vnd.google-apps.spreadsheet' if convert else original_mimetype

file_meta = {'name': 'test.csv', 'mimeType': **body_mimetype**, 'parents': [{'id': myfolder_key}]}
chunk_size = 1024*1024*5
content = <MediaIoBaseUpload object, resumable, 5 MiB chunk size, **original_mimetype**>
req = drive.files().insert(body=file_meta, media_body=content, convert=convert_to_Google_Sheets)
response is None
while not response:
  status, response = req.next_chunk()
  if status:
    print "Uploaded %d%%." % int(status.progress() * 100)

**Comment by sr-murthy** [comment]
Thanks.
