### ISSUE TITLE
Edits listing not committed completely consume Quota

### ISSUE THREAD

**Issue by latas2000** [google/google-api-python-client#155]
Hi Google API Client support. Testing with one of our Games in production, we tried to update the full description of it. The text used in the description exceeded the 4000 chars limit in several cases depending on the language. Using the Python sample to do this it looks the procedure takes all the languages and it is at the end when it tries to do the commit. It is in that moment when I receive a warning that xx-XX language has a full description too long. I fixed the issue of the too long description for that language and I run the script again. Once more there was the same issue but this time for other language. I had to fix this issue 10 times or more, because I was trying to update 44 languages. Never a COMMIT was done, so the listing in the Google Play Development Console never was updated. But when finally I stop receiving messages of too long descriptions, and all languages looks to be compliant, I received the message: Daily save quota exceeded.
So it looks all tries that I had to do to fix the issues and that never could do a complete commit was counted as quota used. So I guess I exceeded the number of changes I can do for a production app in one day.
I guess this is a bug, because in fact no changes were sent to the store ever.

Thank you very much.

**Comment by bantini** [comment]
@latas2000 Did you manage to solve the issue? If not, can you share the code that you were using? Also, can you mention the OS, the python version, and the library version?

**Comment by bantini** [comment]
Closing this assuming the latest version solves this issue. Feel free to reopen this if it comes up again.
