### ISSUE TITLE
It seems like this is missing the measurement protocol

### ISSUE THREAD

**Issue by jonathan-s** [google/google-api-python-client#161]
I can't find it in the documentation nor in the source. It would be great if that was added to the library too.

**Comment by nathanielmanistaatgoogle** [comment]
Your request is rather vague - are you referring to the [Google Analytics Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol)? And are you saying that you'd like to see sample code for it in the `samples` directory of this repository?

**Comment by jonathan-s** [comment]
Hi @nathanielmanistaatgoogle, 
Yes I'm referring to Google Analytics Measurement Protocol and yes I'd like to see some sample code for it. It would be nice with some documentation in the docs section too.

**Comment by mattwhisenhunt** [comment]
Have you seen https://ga-dev-tools.appspot.com/hit-builder/ ? I hope it will help.
