### ISSUE TITLE
MediaIoBaseDownload class is not able to handle "Too Many Requests" error

### ISSUE THREAD

**Issue by nikesh-mahalka** [google/google-api-python-client#162]
I am using ubuntu 14.04.03 server and installed google library with below command:
sudo pip install --upgrade google-api-python-client

google-api-python-client library installed by above command is some commits behind the master branch.

I changed if condition for handling this error in line number 553 in /usr/local/lib/python2.7/dist-packages/googleapiclient/http.py
`if resp.status < 500 and resp.status not in [err1, err2]:` 

And i am able to download a google object by retry mechanism on getting error 429 "Too Many Requests" error.

**Comment by nikesh-mahalka** [comment]
```
from apiclient import http
from apiclient import discovery
from oauth2client import client
import six
credentials = client.GoogleCredentials.from_stream("path-to-json-file")
service = discovery.build('storage', 'v1', credentials=credentials)
req = service.objects().get_media(
            bucket="gcsbucket",
            object='File.exe',)
fh = six.BytesIO()
downloader = http.MediaIoBaseDownload(
            fh, req, chunksize=32768)
done = False
chunk_number = 0
while not done:
    status, done = downloader.next_chunk(num_retries=5)
    chunk_number = chunk_number + 1
    print done, chunk_number
```

Above code was giving too many request error 429, which is now not coming after modifying
https://github.com/google/google-api-python-client/blob/master/googleapiclient/http.py#L99 to
if resp.status < 500 and resp.status not in [err1, err2]:

**Comment by nikesh-mahalka** [comment]
same for uploading a object 
https://github.com/google/google-api-python-client/blob/master/googleapiclient/http.py#L707

retry will not work in "Too many requests error 429".

**Comment by mcdonc** [comment]
This code has been through so many changes by now that the original line of code mentioned by OP no longer exists, and I'm not keen on doing the archaelogy to find the version that was in use when the bug was submitted to do a 3-way comparison.  I'm going to close this as a result; if you find the problem continues to exist in modern versions of google-api-python-client, please reopen.
