### ISSUE TITLE
Support for creating pods and submitting jobs on container engine?

### ISSUE THREAD

**Issue by harche** [google/google-api-python-client#163]
I wasn't able to see any support for being able to submit jobs and creating pods on container engine, is this feature going to be supported in future?

**Comment by nathanielmanistaatgoogle** [comment]
In what documentation are you looking for support and not finding it?

**Comment by harche** [comment]
@nathanielmanistaatgoogle https://developers.google.com/api-client-library/python/

**Comment by nathanielmanistaatgoogle** [comment]
I hate to be the guy who says "you're in the wrong place"... but I think you may be in the wrong place. `google-api-python-client` is a library that is used to programmatically interact with many APIs, but it doesn't actually have much code related to any particular API.

Your support request for those API methods may be more fruitful if made on the [Containers At Google mailing list](https://groups.google.com/forum/#!forum/google-containers)? Have you yet searched the archives of that list to see if anyone else has asked for pod creation and job submission support in the Google Container Engine API?

Please feel free to push back here if I've misunderstood something?

**Comment by mattwhisenhunt** [comment]
Looks like this issue was resolved. I will add another "you're in the wrong place" answer: Have you seen the awesome GCP client being built at https://github.com/GoogleCloudPlatform/google-cloud-python
