### ISSUE TITLE
BatchError is unprintable using default constructor (one string)

### ISSUE THREAD

**Issue by ShadowLNC** [google/google-api-python-client#165]
This one should be pretty simple, I hope.

Here's the constructor signature: `def __init__(self, reason, resp=None, content=None):`, which doesn't require `resp` to be defined, and I can see it is not defined most of the time, for example, in googleapiclient/http.py.

Then, given the representation method:

```
def __repr__(self):
      return '<BatchError %s "%s">' % (self.resp.status, self.reason)
```

Which is also the string method:

```
__str__ = __repr__
```

This results in unprintable exceptions where `resp` is undefined, which is not very helpful when attempting to understand the error (e.g. #164).

**Comment by KillianKemps** [comment]
:+1:  I encountered this same issue. Fortunately, I could fix my problem because you documented another issue #164 very well

**Comment by jonparrott** [comment]
Thanks for reporting this. If anyone wants to send a PR to fix this, I'll be happy to review and merge.
