### ISSUE TITLE
Unable to grant owner access to User members - Cloud Resource Manager API

### ISSUE THREAD

**Issue by ksurya** [google/google-api-python-client#175]
The Cloud Identity and Access Management [documentation ](https://cloud.google.com/iam/docs/managing-policies) mention the following two points that _seem_ to be contradicting each other
- Cloud Resource Manager IAM methods only support granting the owner role to `user` and `serviceAccount`
- A user cannot be granted owner access using `setIamPolicy()`. The user must be granted the owner role using the Cloud Platform Console and he must explicitly accept the invitation.

I am interested to grant owner access to `user` members in a Developer Console project. For this I am using Cloud Resource Manager API. I have tried to implement this in Python and Google Apps Script using Service Account authorization + domain wide delegation. 

In both cases, the program is raising HTTP 400 error with following error:

```

status: INVALID_ARGUMENT
details: "type.googleapis.com/googlecloudresourcemanager.projects.v1beta1.ProjectIamPolicyError", "SOLO_MUST_INVITE_OTHERS".
```

Strangely, I am able to perform this action in Google API Explorer successfully!

So, 

1) Why is this happening? 
2) Is it possible to grant owner access to user members using API?

**Comment by mattwhisenhunt** [comment]
That second point seems to say that is just can't be done programmatically. Is that the method you are successfully calling in API Explorer?

**Comment by JustinBeckwith** [comment]
Greetings!  If this is still an issue, please do let us know!

**Comment by rohithmn3** [comment]
Hi @ksurya ,
I am also facing the same issue;
The below command fails:
`gcloud projects add-iam-policy-binding linuxacademy-3 --member user:rohithmn3@gmail.com --role roles/owner`

Is there any alternative for this; if yes, How to add this in my Python Code.
Please help me here..!

Regards,
Rohith
