### ISSUE TITLE
Separated Python Error object for Rate Limit Error

### ISSUE THREAD

**Issue by vionemc** [google/google-api-python-client#176]
Hi,

Twitter API python library does this, but we don't. Currently, we use HTTPError for this. We have to parse the result first before identifying that it was caused by rate limit. A RateLimitError object will be great.

Thanks,
Ami

**Comment by adrian-the-git** [comment]
Curious how you're parsing them at the moment, the `_get_reason()` method?

**Comment by vionemc** [comment]
Oh, there is that method? Currently I just see if there is `Limit Exceeded` written in the exception string

**Comment by adrian-the-git** [comment]
Yeah, it's the method behind that exception string. I was hoping you'd come up with something better :)

**Comment by vionemc** [comment]
Thanks!

But a separate exception will still be great. To make sure I don't catch any exception I shouldn't catch.

**Comment by mcdonc** [comment]
As the client library talks to many backend APIs (including YouTube) and each one has the opportunity to signify its own type of rate-limiting, and we cannot tie the client library to any particular static set of them for maintainability reasons, I'm going to close this issue.  Please let me know if you think this is in error, but please try to provide some example code changes if you do that give us a clue about how to do this while still retaining maintainability.
