### ISSUE TITLE
ImportError: cannot import name SignedJwtAssertionCredentials

### ISSUE THREAD

**Issue by simonavril** [google/google-api-python-client#193]
I think there might be a problem of version dependency for version 1.4.2.

I had version google-api-python-client==1.4.2 and it used to install oauth2client==1.5.2

But now it installs oauth2client==2.0.0-post1 probably since setup.py says:
```
install_requires = [
    'httplib2>=0.8',
    'oauth2client>=1.4.6',
    'six>=1.6.1',
    'uritemplate>=0.6',
]
```
And then the code does not run anymore:
from oauth2client.client import SignedJwtAssertionCredentials
ImportError: cannot import name SignedJwtAssertionCredentials

**Comment by jonparrott** [comment]
You'll need to upgrade to 1.5.0, as 1.4.2 failed to specify a version range.
