### ISSUE TITLE
Exceeding memcached max key length with httplib2.Http()

### ISSUE THREAD

**Issue by Alex3917** [google/google-api-python-client#195]
The Gmail API recommends enabling cacheing with httplib2.Http() for better performance. The problem I'm running into is that the Google API Python client seems to use the entire API query as the key, which means that long queries fail. E.g. if you are searching Gmail with a list of 10 - 20 different keywords then the memcached max key length will be exceeded and the query will fail.

This might be by design, although in the case of the GMail API only the discovery query is cacheable anyway, so it seems like the full search queries shouldn't be necessary for that to work.

**Comment by jonparrott** [comment]
Can you share a small sample to reproduce this? Is the client library just generating a query string that's too long for httplib2 to cache?

**Comment by Alex3917** [comment]
Correct. The key length limit for memcached is 250 characters, so the querystring the client library generates is just too long for that. If all the info in the querystring is needed then maybe the hash of the querystring could be used as the key. The line that's failing is:

threads = gmail_client.users().threads().list(userId='me', maxResults=15, pageToken=pageToken, q=query).execute()

Where the 'query' variable is a string that's maybe 100 characters long.

**Comment by jonparrott** [comment]
Are there any drawbacks to just disabling caching (other than the obvious)?

**Comment by Alex3917** [comment]
Nope, cacheing is disabled for now and it works fine.

**Comment by jonparrott** [comment]
Okay, so it seems like the bug itself is on httplib2. Does anything need to be done in this library?

**Comment by Alex3917** [comment]
Ahh ok, I guess not then. Thanks!

**Comment by jonparrott** [comment]
Feel free to file this bug (and your proposed solution) over at https://github.com/jcgregorio/httplib2
