### ISSUE TITLE
apiclient.discovery.build crashes Python interpreter (Win10)

### ISSUE THREAD

**Issue by topherredden** [google/google-api-python-client#199]
Running the latest Python 3.5.1 with updated relevant pip packages, I now have build() causing python.exe to crash on Windows. I isolated it down to a simple test script:

```
import platform
import apiclient
from apiclient.discovery import build
print(platform.python_version())
print(apiclient.__version__)
service = build('drive', 'v2')
```

Here is my pip freeze:
```
beautifulsoup4==4.4.1
cffi==1.5.2
cryptography==1.2.3
google-api-python-client==1.5.0
httplib2==0.9.2
idna==2.0
oauth2client==2.0.1
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
PyDrive==1.0.1
PyInstaller==3.1.1
pyOpenSSL==0.15.1
pypiwin32==219
PyYAML==3.11
requests==2.9.1
rsa==3.3
simplejson==3.8.2
six==1.10.0
uritemplate==0.6
```

Nothing is being output (besides my version numbers) so I'm not really sure how to proceed on debugging this.

**Comment by topherredden** [comment]
Since no help came, I just downgraded to version oauth2client==1.4.6 and google-api-python-client==1.4.2 which works fine.

**Comment by jonparrott** [comment]
I don't presently have a windows machine to test one, any additional help with this would be really appreciated.

**Comment by topherredden** [comment]
I did some more digging and it appears to be the same issue as this (https://github.com/google/google-api-python-client/issues/139)

Which is also logged in oauth2client (https://github.com/google/oauth2client/issues/361)

The workaround listed on the oauth2client issue solved the problem for me with the latest versions included. Going to close this since it seems unrelated to the module, but leaving this information here for others.

**Comment by jonparrott** [comment]
Thanks for figuring this out!

Out of curiosity, can you tell me what you're using `multistore_file` for?

**Comment by topherredden** [comment]
I'm not. If you're referring to the work-around, I can only conclude it's being used by oauth2client. If you look at my test code at the top of this issue, that's all that is needed to trigger the crash.

**Comment by jonparrott** [comment]
Oh, right, Thanks. (I should not respond to issues before I've completely woken up)
