### ISSUE TITLE
Drop support for Python2.6

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [google/google-api-python-client#203]
We should do this as early as we can possibly get away with it. Can we get away with it?

**Comment by jonparrott** [comment]
Who would actually know? @craigcitro any insight?

**Comment by craigcitro** [comment]
The only Google tool I know with a 2.6 requirement is gsutil, and they don't use apiclient.

I'm all for dropping 2.6 support, but is there anything that's being actively blocked by this?

**Comment by nathanielmanistaatgoogle** [comment]
@thobrla any reason google-api-python-client can't drop 2.6 support?

**Comment by jonparrott** [comment]
The minute we do remove support someone will come and complain. Do we want to do a release that soft-disables 2.6 and see who yells?

**Comment by nathanielmanistaatgoogle** [comment]
I'd be very receptive to that.

**Comment by jonparrott** [comment]
Do we want to warn or exit here for < 2.7?

https://github.com/google/google-api-python-client/blob/master/setup.py#L24

**Comment by thobrla** [comment]
No objections, gsutil no longer depends on this.  Agreed that someone will probably be impacted, though.

**Comment by nathanielmanistaatgoogle** [comment]
Let's exit. 2.6 was almost eight years ago. 2.7 was almost six years ago.

How about doing a minor version bump to 1.6 and leaving 1.5 still available (until now our PyPI practice has been to hide all earlier versions of the library when releasing a new version)?

**Comment by jonparrott** [comment]
Should this necessitate a bump to 2.0.0?

**Comment by nathanielmanistaatgoogle** [comment]
I don't think it merits a major version bump. There may be some small number of developers affected by the loss of 2.6 support in this library, but every one of them is someone who is inviting larger problems by deliberately running a years-without-security-patches platform.

_2.6's not pinin'! 2.6's passed on! This Python is no more! It has ceased to be! 2.6's expired and gone to meet its maker! It's a stiff! Bereft of life, it rests in peace! If someone hadn't nailed it to the long-term-supported enterprise distribution it'd be pushing up the daisies! Its bytecode executions are now 'istory! 2.6's off the twig! 2.6's kicked the bucket, 2.6's shuffled off its mortal coil, run down the curtain and joined the bleedin' choir invisible!! 2.6 IS AN EX-SOFTWARE INTERPRETER!!_

(With apologies for the strident tone.)

**Comment by jonparrott** [comment]
Fair enough.

**Comment by hugovk** [comment]
This can be closed.

Python 2.6 was dropped in https://github.com/google/google-api-python-client/pull/319. 🎉
