### ISSUE TITLE
Add samples for Google Drive

### ISSUE THREAD

**Issue by Anmol-Singh-Jaggi** [google/google-api-python-client#205]
I believe that there's a dearth of real-life usage examples in the documentation (atleast related to Google Drive); the only sample code I was able to find in the official docs was [this](https://developers.google.com/drive/v3/web/quickstart/python#step_3_set_up_the_sample).  

I want to contribute to this project by adding some real-life usage sample code using the knowledge I gained from making [this project](https://github.com/Anmol-Singh-Jaggi/gDrive-auto-sync), so that other people won't face the same problems that I faced.

So, where do I begin contributing? Do I add the code and the associated tutorial in the `samples` directory?

**Comment by jonparrott** [comment]
@Anmol-Singh-Jaggi you could add them to this library, but it's probably more useful for you and others to publish these samples and tutorials on your own, for discoverability.

**Comment by Anmol-Singh-Jaggi** [comment]
Okay! I guess I can publish it on my blog instead.
You can close the issue if you want.
