### ISSUE TITLE
build throws KeyError: 'rootUrl' error on Google Calendar API

### ISSUE THREAD

**Issue by Ryan-Gouldsmith** [google/google-api-python-client#208]
The below code has recently been throwing a rootUrl error for the Google Calendar v3 API.
```
from apiclient import discovery 
http = credentials.authorize(httplib2.Http())
service = discovery.build("calendar", "v3", http=http)
```
However, the above code using the "plus" "v1" API works fine and returns the correct data. I am using the google-api-python-client version 1.5.0. 

Werkzeug is saying that it's this line which is throwing the error ``` base = urljoin(service['rootUrl'], service['servicePath'])```

**Comment by jonparrott** [comment]
Can you provide us the full stacktrace?

**Comment by Ryan-Gouldsmith** [comment]
This is the stacktrace after the discovery.build....
<img width="1241" alt="screen shot 2016-03-25 at 22 27 30" src="https://cloud.githubusercontent.com/assets/5804107/14055345/21a5fc92-f2d9-11e5-8a31-579ada8dcf55.png">

**Comment by jonparrott** [comment]
I can't seem to reproduce this.

Can you tell me which version you're using? Are you doing anything special in terms of caching or anything?

**Comment by Ryan-Gouldsmith** [comment]
I am using python client 1.5.0. I have come to it this morning and it seems to work. Maybe there was a caching issue with discovery.build ? I will see if it happens again. 

Thanks your help looking into it, I appreciate it.

**Comment by jonparrott** [comment]
Okay, just update this issue if it happens again.

**Comment by aribido** [comment]
I am having issues mocking google-api-client with httpmock. I keep getting:

File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 210, in build
    credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 318, in build_from_document
    base = urljoin(service['rootUrl'], service['servicePath'])
KeyError: 'rootUrl'

Sometimes it works and at other times it doesn't. Can you help find out what could be wrong. 

After I get this error, I cannot use my service-key credentials to authorize again even if I change the .json credential file.

**Comment by ternus** [comment]
The problem seems to be that `build()` will use the provided `http` object to fetch a version of the  when using HttpMock with caching disabled, or when you don't have a cached version of the document (in my case it was on Travis CI, but not on my local machine). Here's a simple script that will reproduce:

```python
#!/usr/bin/env python

from apiclient.discovery import build
from apiclient.http import HttpMockSequence

http = HttpMockSequence([({'status': '200'}, "{}")])
build('calendar', 'v3', cache_discovery=False, http=http)
```

```
Traceback (most recent call last):
  File "reproduce-bug.py", line 7, in <module>
    build('calendar', 'v3', cache_discovery=False, http=http)
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/googleapiclient/discovery.py", line 210, in build
    credentials=credentials)
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/googleapiclient/discovery.py", line 318, in build_from_document
    base = urljoin(service['rootUrl'], service['servicePath'])
KeyError: 'rootUrl'
```

After tearing my hair out, I've discovered a workaround: simply call `build('calendar', 'v3')` with no other arguments before using mocking and it will work fine.

I poked around in the library looking for a fix, but unfortunately this bug-feature is used in the tests. The best I can do is add a warning.

**Comment by eayoungs** [comment]
I'm still getting the same error, even with all the work-arounds listed above. With the same sample code.
--
Python 2.7.12
'_pip list_'
google-api-python-client (1.5.3)
httplib2 (0.9.2)
oauth2client (3.0.0)
pip (8.1.2)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
rsa (3.4.2)
setuptools (26.1.1)
simplejson (3.8.2)
six (1.10.0)
uritemplate (0.6)
wheel (0.29.0)
