### ISSUE TITLE
Calendar api delete event not working

### ISSUE THREAD

**Issue by ttback** [google/google-api-python-client#210]
Sample code:

Note: When I ran following code, the event is technically gone from the Google Calendar UI. There is no indication that the get event part would work. But if it works, at least I should be able to delete it and add another one back.

````
event = service.events().get(calendarId=CALENDAR_NAME, eventId=EVENT_ID).execute()
print(event['summary'])
service.events().delete(calendarId=CALENDAR_NAME, eventId=EVENT_ID).execute()
service.events().insert(calendarId=CALENDAR_NAME, body=EVENT_JSON).execute()
````

Output:

````
event-id

googleapiclient.errors.HttpError: <HttpError 410 when requesting https://www.googleapis.com/calendar/v3/calendars/[group].calendar.google.com/events/714887847573065731? returned "Resource has been deleted">

#It won't really reach the add_event line since delete_event raised an exception, but if I comment out the delete_event line, it will show. 

googleapiclient.errors.HttpError: <HttpError 409 when requesting https://www.googleapis.com/calendar/v3/calendars/[group].calendar.google.com/events?alt=json returned "The requested identifier already exists.">
````

So I can get an event's data but unable to either delete_event and add_event...I also do not see the deleted event on the Google calendar, but I am unable to add new event with same identifier. 

Update: The cause was that Google Calendar has added the Trash feature can in November, 2015...so I am not sure if the API supports this.

**Comment by jonparrott** [comment]
I'm not overly familiar with the Google Calendar API, but I don't think you should try to determine the resource ids yourself. If you want to insert an identical even, you should trip the ID from the request.

Also, in general this issue tracker is for issue related directly to the client library, not necessarily the APIs themselves. Stackoverflow is the best place for questions like this.

(I'm going to close this issue, as it's unlikely that anyone who works directly on this client library can further assist, but if you have any other questions related to this issue that you think we can help with feel free to comment).
