### ISSUE TITLE
Cannot access shared dataset

### ISSUE THREAD

**Issue by onedeadear** [google/google-api-python-client#215]
What steps will reproduce the problem?
1. Create a dataset in one project in account (a)
2. Share this dataset with a project in another account (b)
3. Create a service account in account b and give it view or editor permissions
4. Attempt to list the tables in the shared dataset using the python API

What is the expected output? What do you see instead?

I expect to see the list of tables for the shared dataset. Instead I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/googleapiclient/http.py", line 760, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/bigquery/v2/projects/<projectId>/datasets/<datasetId>/tables?alt=json returned "Access Denied: Dataset <projectId>:<datasetId>: The user <service account email> does not have permission to list tables in dataset <projectId>:<datasetId>">

What version of the product are you using? On what operating system?

OS:
CentOS release 6.7 (Final)

Python packages:
google-api-python-client (1.5.0)

Please provide any additional information below.

Using the user account (project owner) I can list the tables in the dataset using the UI or the bq command line tool

**Comment by jonparrott** [comment]
It might be better to ask this question on stackoverflow, as this team does not maintain the APIs themselves, just the client library. Authorization issues are unfortunately out of our area of focus.
