### ISSUE TITLE
Seriously out of date - http://api-python-client-doc.appspot.com/

### ISSUE THREAD

**Issue by jonathan-s** [google/google-api-python-client#217]
The documentation hosted there is seriously out of date. Though it seems like the docs in the file docs/epy is rather up to date and from my understanding that's where the docs at the url come from.

**Comment by jonparrott** [comment]
Why close this issue?

**Comment by jonathan-s** [comment]
Because I made an embarassing mistake. :) The url I meant was this one: http://google-api-python-client.googlecode.com/hg/docs/epy/module-tree.html That is indeed completely out of date. Don't remember exactly how I ended up there though.

**Comment by nathanielmanistaatgoogle** [comment]
According to [this](http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html), that URL shouldn't be serving anything anymore. Hmm...

**Comment by jonathan-s** [comment]
@JustinBeckwith, not sure there is anything I can do? I'm not bothered by this any longer so leaving it closed is what we should do in my opinion.

**Comment by JustinBeckwith** [comment]
Apologies - this was a robot run amok 🤖  Feel free to ignore!
