### ISSUE TITLE
YouTube Reporting media().download(...) generates request with invalid query parameter

### ISSUE THREAD

**Issue by AlexRiina** [google/google-api-python-client#226]
When I generate a request for a report with `.media().download(resourceName="test")`, the uri is `https://youtubereporting.googleapis.com/v1/media/test?alt=json` but the request fails with the following error:

```
[{
  "error": {
    "code": 400,
    "message": "Invalid value for query parameter 'alt'. It must be set to \"media\".",
    "errors": [
      {
        "message": "Invalid value for query parameter 'alt'. It must be set to \"media\".",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
]
```

if I manually change that to `media` while running the query, unfortunately it still fails with 

```
[{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
]
```

I'd be happy to file a separate issue for that if it makes sense.

**Comment by AlexRiina** [comment]
I see now that the sample code has something along the lines of

```
request = resource.media().download(resourceName="")
request.uri = job_url  # from jobs().reports().list()
... MediaIoBaseDownload
```

**Comment by j450h1** [comment]
Did you get this to work somehow by modifying the url?

**Comment by AlexRiina** [comment]
Yeah. I followed along with `def download_report` from https://developers.google.com/youtube/reporting/v1/code_samples/python#retrieve_reports and got it working

**Comment by yinleon** [comment]
after 2017/01/05 I started getting this error 
```TypeError: Parameter "resourceName" value "" does not match the pattern "^.+$"```
with a line that's been working for months....
```resource.media().download(resourceName="")```
This was fixed by adding a space between the quotes.

Any idea what happened? Can anyone re-create this issue?

**Comment by soyamagic** [comment]
@yinleon 
I get same error.
If possible, I'd like to know the reference that explains the method
```
resource.media().download(resouceName="")
``` .
I don't find where it is.

**Comment by ebragas** [comment]
I was having the same exact issue @yinleon. Adding the space between quotes also fixed it.

**Comment by ajhsieh** [comment]
Same issue, same workaround as @yinleon and @ebragas

**Comment by bantini** [comment]
Closing this because the workaround solved the problem.

**Comment by mcdonc** [comment]
It appears that the solution to this, which is currently documented as canon in the download_reports function at  https://developers.google.com/youtube/reporting/v1/code_samples/python#retrieve_reports is to pass a non-empty value as resourceName (a single space character).

If this seems unreasonable, please comment, and we will consider reopening.  Thanks a lot for the bug report and apologies for the long wait.
