### ISSUE TITLE
Google Keep API

### ISSUE THREAD

**Issue by ttufts** [google/google-api-python-client#227]
Users have been begging for a Google Keep API for decades. Please can we have one? I have dozens of ideas for ways I would use a Keep api. What if I say pretty please?

https://code.google.com/p/google-apps-script-issues/issues/detail?can=2&start=0&num=100&q=&colspec=Stars%20Opened%20ID%20Type%20Status%20Summary%20Component%20Owner&groupby=&sort=&id=3477

http://stackoverflow.com/questions/19196238/is-there-a-google-keep-api

https://www.reddit.com/r/google/comments/1ufwyu/is_there_a_google_keep_api_looking_to_build_a/

**Comment by jonparrott** [comment]
We just support the API client, we do not support the APIs themselves. Within Keep, there should be a way to send product feedback, I recommend using that channel to make this request.

**Comment by juanmiguelRuaDev** [comment]
It would be interesting because I want to make an application to carry through the migration of my evernote notes to google keep.

**Comment by JulienGenoud** [comment]
that would be fabulous idea to put a keep public api !
@jonparrott who sould be contacted ?

**Comment by jonparrott** [comment]
This has already been requested through all the correct channels. There's nothing the maintainers of this library can do to move that along, it is completely up to the product team.

**Comment by JulienGenoud** [comment]
ok thanks

**Comment by day-aaron** [comment]
I'm throwing in +1 for the api.

**Comment by Sasoon** [comment]
Another +1 for the api

**Comment by gnumoksha** [comment]
+1
