### ISSUE TITLE
Does support latest Python 3 version: 3.5 or 3.5.1?

### ISSUE THREAD

**Issue by SalvaJ** [google/google-api-python-client#233]
As subject says.

I want to use this module with Python ver. 3.5.1.  I need to use the Google API for Drive.

**Comment by nathanielmanistaatgoogle** [comment]
We haven't yet updated our continuous integration to test `google-api-python-client` in a 3.5 environment, but we aren't aware of any incompatibilities (and we would fix any brought to our attention).

Please consider Python 3.3 _and all later versions_ suppported.

**Comment by impredicative** [comment]
If 3.5 is supported, why is it not listed under Categories at https://pypi.python.org/pypi/google-api-python-client/ ?
