### ISSUE TITLE
list search endpoint only returning 500 results

### ISSUE THREAD

**Issue by awlamb** [google/google-api-python-client#236]
The list search endpoint for the google api python client only returns 500 results max, even though the totalResults lists one million. There's some info out there about this being expected behavior but I can't really see why. Is this fixable?

**Comment by jonparrott** [comment]
APIs themselves often have backend limits in place, so usually it's something like `min(user_specified_max, internal_limit)`. In general, you should always expect that fewer results than requested may be returned.
