### ISSUE TITLE
Google drive changes returns 404

### ISSUE THREAD

**Issue by ralka** [google/google-api-python-client#238]
Hello,

we have a web prototyping tool where some of the users sync their images from Google Drive. This means that they add an image to the prototype and then work using whatever tool they fancy and the changes are synced via Google Drive. 

We have always received an overwhelming amount of 404s after being hit by a webhook, because a file has presumably changed. We have made our piece with that, and there are no docs or info to be found where we could understand more about the mechanics of how all this works. If there is one, please, point me in its direction. 

I found an obscure StackOverFlow post that claims that with every file change the previous one is cancelled and this is why it returns 404s. It makes sense, and as long as we eventually get the change we are happy. 

However, even this stopped working and sometimes a file will never be updated. We get hit by the webhook but the request always 404s. Same file is correctly updated in the Google Drive webview.

A basic example from our logs:

INFO       2016-06-09 11:59:20,944 tasks:120 check_drive_change 676dc142-5f17-4e05-82f1-63cfcb0b8979
INFO       2016-06-09 11:59:20,945 tasks:121 check_drive_change {u'kind': u'drive#change', u'id': u'380', u'selfLink': u'https://www.googleapis.com/drive/v2/changes/380'}
INFO       2016-06-09 11:59:21,351 tasks:150 check_drive_change drive.webhook.change.404.380

INFO       2016-06-09 12:09:34,963 tasks:120 check_drive_change 676dc142-5f17-4e05-82f1-63cfcb0b8979
INFO       2016-06-09 12:09:34,963 tasks:121 check_drive_change {u'kind': u'drive#change', u'id': u'383', u'selfLink': u'https://www.googleapis.com/drive/v2/changes/383'}
INFO       2016-06-09 12:09:35,279 tasks:150 check_drive_change drive.webhook.change.404.383

INFO       2016-06-09 12:12:28,127 tasks:120 check_drive_change 676dc142-5f17-4e05-82f1-63cfcb0b8979
INFO       2016-06-09 12:12:28,127 tasks:121 check_drive_change {u'kind': u'drive#change', u'id': u'386', u'selfLink': u'https://www.googleapis.com/drive/v2/changes/386'}
INFO       2016-06-09 12:12:28,467 tasks:150 check_drive_change drive.webhook.change.404.386

INFO       2016-06-09 12:12:51,186 tasks:120 check_drive_change 676dc142-5f17-4e05-82f1-63cfcb0b8979
INFO       2016-06-09 12:12:51,186 tasks:121 check_drive_change {u'kind': u'drive#change', u'id': u'389', u'selfLink': u'https://www.googleapis.com/drive/v2/changes/389'}
INFO       2016-06-09 12:12:51,466 tasks:150 check_drive_change drive.webhook.change.404.389

INFO       2016-06-09 12:16:41,089 tasks:120 check_drive_change 676dc142-5f17-4e05-82f1-63cfcb0b8979
INFO       2016-06-09 12:16:41,089 tasks:121 check_drive_change {u'kind': u'drive#change', u'id': u'392', u'selfLink': u'https://www.googleapis.com/drive/v2/changes/392'}
INFO       2016-06-09 12:16:41,511 tasks:150 check_drive_change drive.webhook.change.404.392

676dc142-5f17-4e05-82f1-63cfcb0b8979 is the channel for the file. The kind is change: u'kind': u'drive#change', and then it 404s for the id we received via the webhook. 

I have no idea where to look for an answer or how to go about trying to change or troubleshoot somehow. 
We are using google-api-python-client==1.4.0
Anybody has any idea why this is happening?

Thanks

Rali

**Comment by jonparrott** [comment]
Unfortunately we do not maintain the APIs themselves, only this client.

I would recommend filing a bug on the [public issue tracker](https://code.google.com/a/google.com/p/apps-api-issues/) for Apps APIs.

**Comment by ralka** [comment]
Thanks, Jon. I was pretty sure this was not the right place to post as we have no issues with the library itself, but at the same time had no idea where to post.

**Comment by jonparrott** [comment]
Hopefully you can find some answers!
