### ISSUE TITLE
init() function of sampletools.py not useful when discovery document is not accessible via URL

### ISSUE THREAD

**Issue by jaybeeo** [google/google-api-python-client#24]
For non-public APIs, the discovery document is not accessible via URL, thus it is necessary to use a local file instead. The problem is that sample_tools does not support doing so.

Adding an optional discovery_filename param to init() would allow calling discovery.build_from_document() instead of the default discovery.build().

**Comment by bantini** [comment]
Closing this because this library is in maintenance mode and we are not adding new features at this moment. Please feel free to reopen this issue if there is a major problem.

**Comment by bwarner-nf** [comment]
It looks like this was addressed in: the following commit: 
[63caac0](https://github.com/googleapis/google-api-python-client/commit/63caac01ea7b9fbd8ae70bcbb4c6ecbec833ad3d#diff-380df39541e6061ebfb98cf8d2da4168)
