### ISSUE TITLE
HttpError 416 On 0 byte files

### ISSUE THREAD

**Issue by znorris** [google/google-api-python-client#241]
When attempting to download the first chunk of a 0 byte file `googleapiclient.http.MediaIoBaseDownload()` throws a `googleapiclient.errors.HttpError`. Modifying the default `chunksize` does not help.

However, if you remove the [header](https://github.com/google/google-api-python-client/blob/master/googleapiclient/http.py#L664) entirely (downloading without chunking) a 0 byte file can be downloaded without receiving a HTTP 416 error.

I'm not sure what anyone thinks of this solutions but currently we're [checking](https://github.com/google/google-api-python-client/blob/master/googleapiclient/http.py#L666) for HTTP `200` and `206` response codes before writing the content to file, should we add a condition for `416`?

**Comment by Rawing** [comment]
Not sure if I should open a new bug for this one, but there's a similar bug when trying to upload 0 byte files:

```
fd= BytesIO()
media = googleapiclient.http.MediaIoBaseUpload(fd=fd, chunksize=128, mimetype='text/plain', resumable=True)
body = {'name' : 'foo.txt'}
service.files().create(body=body, media_body=media, fields='id').execute()
```

Throws

`googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id&uploadType=resumable returned "Bad Request">`

**Comment by mcdonc** [comment]
The original bug appears to now be fixed (verified by uploading empty file to Drive, then using MediaIoBaseDownload to download it successfully).  I'm closing this issue as a result, thanks so much for the report.
