### ISSUE TITLE
NameError: name 'api' is not defined

### ISSUE THREAD

**Issue by loverofsheep** [google/google-api-python-client#242]
I'm a beginner so the laconic version of any instruction would be great. I'm trying to build a twitter bot using heroku but when I run the worker I receive this error.

`Running worker on ⬢ enigmatic-dusk-70524... up, run.1584
>>> Generating from wildhogsscript.txt
Traceback (most recent call last):
  File "ebooks.py", line 127, in <module>
    status = api.PostUpdate(ebook_tweet)
NameError: name 'api' is not defined`

The issue is on this part of the code

```
           if DEBUG == False:
                status = api.PostUpdate(ebook_tweet)
                print status.text.encode('utf-8')
            else:
                print ebook_tweet`
```

I don't understand why it says the name is not defined because it is defined with this earlier code. The consumer keys and access tokens are defined in a separate document.

````
def connect():
    api = twitter.Api(consumer_key=MY_CONSUMER_KEY,
                          consumer_secret=MY_CONSUMER_SECRET,
                          access_token_key=MY_ACCESS_TOKEN_KEY,
                          access_token_secret=MY_ACCESS_TOKEN_SECRET)`
```

I've made a bot using this code before so I don't know why it isn't working. I don't know a lot about programming or python but I could sure use someones help if you've got the time. If this is the improper place to put this just let me know and I'll take the issue elsewhere. Thank you!

**Comment by jonparrott** [comment]
It seems your issue is that you defined ``api`` within the scope of ``connect`` but tried to use it from outside of that scope. 

Maybe see [here](https://www.safaribooksonline.com/library/view/learning-python/1565924649/ch04s03.html)?
