### ISSUE TITLE
get 400 errors when use MediaUpload with minetype='application/vnd.google-apps.video' to upload google drive

### ISSUE THREAD

**Issue by alochym01** [google/google-api-python-client#244]
Hi list

i read the doc of google drive v3 and upload the video with minetype=application/vnd.google-apps.video

media = MediaFileUpload('files/report.csv',  mimetype='application/vnd.google-apps.video',  resumable=True)

i get 400 errors

https://developers.google.com/drive/v3/web/manage-uploads#importing_to_google_docs_types_wzxhzdk8wzxhzdk9

what minetype for video the google api client support to work with google drive

thank you

**Comment by jonparrott** [comment]
I'm not an expert on the Google Drive API and you might be better off asking this question on stackoverflow, as the people who maintain this library just maintain the library and not the APIs themselves.

However, I think you need to upload the file as it's normal mime type, e.g., 'video/mp4'. I don't think you can upload Google Docs mimetypes directly.

**Comment by alochym01** [comment]
just testing with set the minetype='video/*' it works properly

Thank you
Ha`
