### ISSUE TITLE
Using BatchHttpRequest with ETag caching

### ISSUE THREAD

**Issue by superciccio14** [google/google-api-python-client#249]
I'm trying to understand if it is possible to use `BatchHttpRequest` with `ETag` caching.
I'm quite new to Python then sorry if my question is trivial. My conundrum is if it is possible to add to the batch a lot of `list` (i.e., `GET`) requests and also to cache results for further batch calls.

PS:There is also a question active on [stackoverflow](http://stackoverflow.com/questions/37797374/google-api-client-python-is-it-possibile-to-use-batchhttprequest-with-etag-ca/38168154?noredirect=1#comment63821448_38168154). Hope that is not a problem.

**Comment by jonparrott** [comment]
As you discovered on StackOverflow, BatchHttpRequest is just for POST, therefore it won't do any caching.
