### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jakirkham** [google/google-api-python-client#252]
This [file]( https://github.com/google/google-api-python-client/blob/35aadaa8adca88b6d6da868dd32856e657176948/googleapiclient/mimeparse.py#L3 ) says it is is under MIT. However, the [license]( https://github.com/google/google-api-python-client/blob/35aadaa8adca88b6d6da868dd32856e657176948/LICENSE ) says Apache 2.0. Is that file suppose to say MIT? Should the license be updated to note this?

**Comment by jonparrott** [comment]
The mimeparse file itself might have originally been under MIT license.
This library is under the Apache 2 license.
