### ISSUE TITLE
Error message optional_warn_function.func_name = f.func_name     AttributeError: 'function' object has no attribute 'func_name'

### ISSUE THREAD

**Issue by idesignedme** [google/google-api-python-client#254]
I am trying to use the google client api for python 3.5 but only 3.4 is supported I keep getting the error messag

optional_warn_function.func_name = f.func_name
    AttributeError: 'function' object has no attribute 'func_name'

is there a work around or will the version compatible with 3.5 be coming out soon ?

**Comment by jonparrott** [comment]
Can we get a full stacktrace here so we know where this occurred?

Additionally, I'm happy to review any PRs to fix this.

**Comment by idesignedme** [comment]
@jonparrott heres what I get if I use python shell and try to import it. I get this error message

Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/gdata/__init__.py", line 27, in <module>
        import atom
      File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/atom/__init__.py", line 133, in <module>
        CreateClassFromXMLString)
      File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/atom/__init__.py", line 97, in mark_deprecated
        optional_warn_function.func_name = f.func_name
    AttributeError: 'function' object has no attribute 'func_name'

**Comment by jonparrott** [comment]
Gotcha. Seems like func_name is gone in 3.5. Should be an easy fix. Happy to review and PRs to fix it.

**Comment by idesignedme** [comment]
@jonparrott how do I go about this I'm new to programming even newer to using git hub. How do I make a pull request?

**Comment by jonparrott** [comment]
@idesignedme welcome to open-source. I can try to point you in the right direction, but there's a lot of stuff to cover!

I'd recommend starting with [github's guide](https://help.github.com/categories/collaborating-on-projects-using-issues-and-pull-requests/) on collaborating. :)

**Comment by WinterIsComming** [comment]
Hi Any solution for this error

**Comment by mcdonc** [comment]
This bug is filed against the wrong repository, I believe.  It should be in https://github.com/google/gdata-python-client .  I think there may be an official way to move it there, but it's not immediately obvious how to do that.

**Comment by mcdonc** [comment]
This issue was moved to google/gdata-python-client#65

**Comment by mcdonc** [comment]
I used https://github-issue-mover.appspot.com/ to move the issue
