### ISSUE TITLE
Service account key not refreshing token

### ISSUE THREAD

**Issue by jsimeroth** [google/google-api-python-client#259]
Hi I am trying to use a google Service Account Key, Other, json file to continually update a google spread sheet with gspread. it works for one hour(the lifespan of the token) then stops. The token dose not refresh. I have no idea why its not working. I could really use an exact example of how to get my script to always run. Thank you.

**Comment by jonparrott** [comment]
The credentials should automatically refresh. Can you provide us with a stacktrace or more details?

**Comment by jsimeroth** [comment]
Hi @jonparrott  Yes, sorry about that. I get an - Invalid token: Statless token expired error. I am running this code on a Raspberry Pi running raspbian jessie, with proximity sensors to detect when printers are printing or in home position I am using Pythong 2.7x(was having issues with gspread in Python 3.x) the code I am using for using the Service Account Key is ass follows.  Thank you for response and help.

`import gspread
from oauth2client.service_account import ServiceAccountCredentials
import httplib2
from httplib2 import Http

scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name(filename.json,scope)
gc = gspread.authorize(credentials)
wks = gc.open('spreadsheet name')
p1 = wks.worksheet('Printer One')

def functon()
 ....
 p1.append_row(printing)`

**Comment by jsimeroth** [comment]
Hi Jon, I made a response to your question in the issue, right below your
comment.

Thank you.

**Comment by jonparrott** [comment]
It seems you're using gspread instead of this library. Since gspread isn't using this library and appears to be using requests, it's possible it's not using the underlying oauth2client logic to refresh.

I'd suggest submitting a bug to [gspread](https://github.com/burnash/gspread).
