### ISSUE TITLE
Documentation: Google People API Python quick start example produces invalid scope

### ISSUE THREAD

**Issue by PeterMarshallAu** [google/google-api-python-client#260]
Regarding documentation page: https://developers.google.com/people/quickstart/python

In the quick start example, the line
`SCOPES = 'https://www.googleapis.com/auth/contact.readonly'
`
suggest changing to:
`SCOPES = 'https://www.googleapis.com/auth/contacts.readonly'
`

Without that change, it was giving an invalid scope error.
```
Error: invalid_scope

Some requested scopes were invalid. {invalid=[https://www.googleapis.com/auth/contact.readonly]}
```

Python 2.7
Ubuntu 16.04 LTS
Firefox 48.0

**Comment by nathanielmanistaatgoogle** [comment]
This fix, made internally at Google, is now live at https://developers.google.com/people/quickstart/python.

Thank you for reporting the problem!
