### ISSUE TITLE
OAuth2Client 3.0 replaces util with _helpers

### ISSUE THREAD

**Issue by hugodro** [google/google-api-python-client#262]
Any 'from oauth2client import util' fails on v3.0 of the library as the 'util.py' has been moved to '_helpers.py'.  Replacing all call to 'util.' to '_helpers.' fixes the problem.

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle seems we only use the dreaded `positional` here.

**Comment by nathanielmanistaatgoogle** [comment]
I'm open to a conditional import for the moved code element.

**Comment by jonparrott** [comment]
That's what I'll do.
