### ISSUE TITLE
compute.instances().setMetaData(...) seems to not exist. setTags works.

### ISSUE THREAD

**Issue by LordNacho** [google/google-api-python-client#271]
It's as if it hasn't been generated by whatever you're using to automate the API calls.

When I do compute.instances().setMetadata(...), it gives me an attribute error, saying setMetadata doesn't exist.

When I slightly modify the call to use setTags, it works just fine.

**Comment by jonparrott** [comment]
We generate it from the upstream discovery document. It seems this method [does exist](https://developers.google.com/apis-explorer/#p/compute/v1/compute.instances.setMetadata)

```python
>>> import googleapiclient.discovery
>>> compute = googleapiclient.discovery.build('compute', 'v1')
>>> compute.instances().setMetadata
<bound method Resource.method of <googleapiclient.discovery.Resource object at 0x10c7f0510>>
```

**Comment by LordNacho** [comment]
Perhaps I'm calling it wrong. I'll check again in the morning.
