### ISSUE TITLE
Provide Bazel BUILD target

### ISSUE THREAD

**Issue by pames** [google/google-api-python-client#275]
Bazel workspaces provide a way to import third party code / libraries via git_repository rules:

https://www.bazel.io/versions/master/docs/be/workspace.html#git_repository

It would be nice if google-api-python-client exposed a BUILD file so Bazel users could depend on / link it in to their projects easily.

**Comment by pames** [comment]
In the meantime I might try some workaround involving the new_http_archive rule and this PyPi artifact:

https://pypi.python.org/pypi/google-api-python-client/

but it would be nice to just import / build using this repository directly.

**Comment by jonparrott** [comment]
I'm open to PRs that add this functionality, but I do not have the domain knowledge required or the time available to investigate this personally.

**Comment by pames** [comment]
OK, so this can be worked around temporarily in the following way:

1) add new_http_archive() repositories to WORKSPACE for this library and its transitive dependencies, e.g.:
```new_http_archive(
  name = "google_api_python_client_archive",
  url = "[...]",
  sha256 = "d916e04969cb1fd6727b9f49290828e9d7162b90c1d5b4be0aed3c171a75d8be",
  strip_prefix = "google-api-python-client-1.5.3",
  build_file = "BUILD.google_api_python_client"
)
```

do this for httplib2, oauth2client, uritemplate

2) Create the respective BUILD.<dependency> files for the archives, lazy example that does not break up into tests/etc. below:
```
py_library(name="gpyclient",
          srcs = glob(["googleapiclient/**/*.py"]),
          visibility = ["//visibility:public"],
          )
```
3) Create a meta-target in your own BUILD file (this can all probably be consolidated into the BUILD.google_python.... file):
```
py_library(
    name = "gpython_lib",
    deps = ["@google_api_python_client_archive//:gpyclient",
            "@httplib2_archive//:httplib2",
            "@oauth2client_archive//:oauth2client",
            "@uritemplate_archive//:uritemplate",
    ]
)
```
4) profit (I can call discovery.build('discovery', 'v1').apis().list().execute())

I would hope that if a WORKSPACE is added to the base here and BUILD as well with these targets (maybe with more restricted visibility) it could be imported by other bazel workspaces but I have seen some things in the issue tracker that seem related to resolving cross-workspace imports so it might be finicky / may require a different approach.

My immediate problem is solved so I don't plan to work on this more at the moment - but hopefully this is helpful if anyone else is interested in this capability.

**Comment by jonparrott** [comment]
Great. If you don't mind, I'm going to close this issue since there is a workaround. Thanks for the detailed post.

If/when in the future there is enough demand for this feature, we can re-open. :)

**Comment by nathanielmanistaatgoogle** [comment]
I'm excited about this happening... sometime. I also lack time to work on it myself.

**Comment by blais** [comment]
It would be great for all the Google OSS projects to support Bazel build by default.
