### ISSUE TITLE
Fetch all available application

### ISSUE THREAD

**Issue by bolom** [google/google-api-python-client#276]
How fetch all available application for a specific google developer account with the lib?

**Comment by jonparrott** [comment]
Can you be a bit more specific? Which API are you using?

In general, issues on this project are against the API client itself and not the APIs that it talks to. Support for those APIs are typically handled on StackOverflow.

**Comment by bolom** [comment]
Google Play API. I would like to fetch all the app for a specific client. I have checked the samples in github. I don't see anything relating to my issue

**Comment by jonparrott** [comment]
Unfortunately there's no one who works on this project that will be able to answer any questions about that specific API. I'd recommend asking your question on stackoverflow with the Google Play API tag.
