### ISSUE TITLE
Authenticate without browser

### ISSUE THREAD

**Issue by rahulsingh303** [google/google-api-python-client#279]
Hi,

I am using DCM/DFA Python API , it uses google api to authenticate using OAUTH 2.0 . I used the sample python scripts , however problem is the scripts tries to open a browser to authenticate , this works on my local laptop but a problem when we try to run from a ETL service on a Linux image , there's no way I will have access to give any input either through command prompt or browser , thus is there any way in oauth2.0 which can pre-authenticate and that can be stored somewhere so that scripts just run and do not try to open a browser ?

Please help .

Regards
Rahul Singh

**Comment by jonparrott** [comment]
You can store the refresh token and refresh the credentials from anywhere, you can also look into using service account authentication which does not require user interaction.

**Comment by jonparrott** [comment]
Some resources:

https://developers.google.com/api-client-library/python/guide/aaa_oauth
https://developers.google.com/api-client-library/python/auth/service-accounts

**Comment by rahulsingh303** [comment]
Thanks for a quick response , I will check it out and see if it works .
