### ISSUE TITLE
UnicodeDecodeError in discovery.createNextMethod()

### ISSUE THREAD

**Issue by flememl** [google/google-api-python-client#28]
The `request.uri` string might be converted to unicode (because of concatenation).

There is a failsafe in `models.BaseModel._build_query()` but not in `discovery.createNextMethod()`, so when calling `search.list` with `q="pasión"`, the call to `search.list_next` raises a `UnicodeDecodeError`.

Suggested fix:
in `googleapiclient/discovery.py:842`

``` python
pageToken = previous_response['nextPageToken']
try:
    uri = request.uri.encode('utf-8')
except UnicodeDecodeError:
    uri = request.uri
parsed = list(urlparse.urlparse(uri))
q = parse_qsl(parsed[4])
```

**Comment by pete0877** [comment]
This still seems to be an issue in 1.4.  Any update on when this issue might be addressed?

Following fork fixed it for us (thanks @flememl flememl):

```
    pageToken = previous_response['nextPageToken']

    # NEW:
    #########
    try:
        uri = request.uri.encode('utf-8')
    except UnicodeDecodeError:
        uri = request.uri
    parsed = list(urlparse(uri))
    #########

    # OLD:
    #######
    # parsed = list(urlparse(request.uri))
    #######

    q = parse_qsl(parsed[4])
```

**Comment by bantini** [comment]
Closing this issue because there has been no more discussion on this. Please feel free to reopen the issue if the problem re-appears.
