### ISSUE TITLE
documentation type miss (Compute Engine API)

### ISSUE THREAD

**Issue by tanan** [google/google-api-python-client#282]
In the "Compute Engine API > images > insert > sourceDisk", I found type miss in the following examples.
"# - https://www.googleapis.com/compute/v1/projects/project/zones/zone/disk/disk"
"# - projects/project/zones/zone/disk/disk"

The correct is "disks/disk". please fix it.

URL:
https://developers.google.com/resources/api-libraries/documentation/compute/v1/python/latest/compute_v1.images.html

**Comment by nathanielmanistaatgoogle** [comment]
Thank you for the report; I have relayed it inside Google and will try to see that it finds the right people and gets fixed.
