### ISSUE TITLE
Crash on processing the response of an uploaded chunk

### ISSUE THREAD

**Issue by dtheodor** [google/google-api-python-client#283]
The following crash happens, rarely but surely, when uploading files on google drive. I am using library version 1.5.1 but I don't see any changes to that part of the code if I compare to the latest.

I am calling `execute` (not `next_chunk`) on a resumable upload, which internally calls `next_chunk` so I don't think it makes a difference:

``` python
media_upload = MediaFileUpload(path, resumable=True)
body = {...}
service.files().insert(body=body, media_body=media_body).execute()
```

Traceback:

```
  File "/project/file.py", line 115, in execute
    return HttpRequest.execute(self, http=http, num_retries=num_retries)
<...>
  File "/project/eggs/oauth2client-2.2.0-py2.7.egg/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/project/eggs/google_api_python_client-1.5.1-py2.7.egg/googleapiclient/http.py", line 919, in next_chunk
    status, body = self._process_response(resp, content)
  File "/project/eggs/google_api_python_client-1.5.1-py2.7.egg/googleapiclient/http.py", line 993, in _process_response
    self.resumable_progress = int(resp['range'].split('-')[1]) + 1
KeyError: 'range'
```

What's obviously happening is that the 308 response returned by the google server sometimes does not return any `range` key, but the client code assumes that a `range` key will always be there on a 308 response.

https://github.com/google/google-api-python-client/blob/70d03943e3a36983866fe40947aef79a16892ec3/googleapiclient/http.py#L990-L993

Is this a client bug (as in not correctly implementing the API specification), or just a bad reply from the server that can be solved by retying the request?

**Comment by dtheodor** [comment]
Here's a server response that causes this, missing the `'range'` key

```python
{
	'status' : '308',
	'content-length' : '0',
	'server' : 'UploadServer',
	'x-guploader-uploadid' : 'AEnB2UqO3RJ6t-RmdXYORev8I6fRS7PXLp4U5KTn0YEjK8JGvwoXVzRGRiiuN4m47dgbAdotimxf2B90Dup_ZwjH1OUia0S-X-u8Q0Vqi-rYPGNRo08CwQs',
	'date' : 'Mon, 10 Oct 2016 01:18:53 GMT',
	'alt-svc' : 'quic=":443"; ma=2592000; v="36,35,34,33,32"',
	'content-type' : 'text/html; charset=UTF-8'
}

```

**Comment by saaros** [comment]
I believe this is fixed in 94a539406fb18bf59861f64904d1f82b02659b61

**Comment by dtheodor** [comment]
If this fix results in restarting the resumable upload from byte 0 then yes

**Comment by jonparrott** [comment]
@dtheodor @saaros if either of you can confirm the fix, I'll close.
