### ISSUE TITLE
no locked_file in oauth2client/contrib gives an import Error in discovery_cache/file_cache.py

### ISSUE THREAD

**Issue by pacobuenaparte** [google/google-api-python-client#296]
With oauth2client version 4.0.0, there is no more oauth2client/oauth2client/contrib/locked file.py

Hence, in google-api-python-client/googleapiclient/discovery_cache/file_cache.py , the code
```
try:
  from oauth2client.contrib.locked_file import LockedFile
except ImportError:
  # oauth2client < 2.0.0
  from oauth2client.locked_file import LockedFile
```
gives an ImportError.

**Comment by jonparrott** [comment]
@pacobuenaparte the latest version of this library [specifies](https://github.com/google/google-api-python-client/blob/master/setup.py#L67) that it is not compatible with oauth2client 4.0.0.

**Comment by samuscurious** [comment]
@jonparrott 
[install_requires](https://github.com/google/google-api-python-client/blob/master/setup.py#L67) doesn't seem to show incompatibility with 4.0.0. 

'oauth2client>=1.5.0,<5.0.0dev'
Wouldn't '4.0.0' fall under '<5.0.0dev'?

Thanks.

**Comment by jonparrott** [comment]
@samuscurious sorry, I should've been more specific. This library is compatible with oauth2client 4.0.0, but the disk-based cache is not.

**Comment by samuscurious** [comment]
@jonparrott Oh! Interestingly, the locked_file import issue went away for me after downgrading from 4.0.0. That apparently means the incompatibility part of the versions is true. Don't know what to say.
