### ISSUE TITLE
Suggest use of httplib2 v0.9.2 in readme if using python > 3

### ISSUE THREAD

**Issue by sloan-dog** [google/google-api-python-client#300]
Python3.x implementations of the client, passes bytestring to httplib2 header encoding method. Httplib2 < 0.9.2 does not support this. 

Documentation should make a note that implementations in python3 should explicitly install httplib2 0.9.2. PyPi index targets 0.8.0, which is no bueno for those unaware of this issue.

**Comment by jonparrott** [comment]
@sloan-dog do you think we should just bump the minimum version up in [`setup.py`](https://github.com/google/google-api-python-client/blob/master/setup.py#L66)?

**Comment by sloan-dog** [comment]
@jonparrott That sounds like a good out-of-the-box fix.
