### ISSUE TITLE
Version management in Cloud SDK

### ISSUE THREAD

**Issue by znorris** [google/google-api-python-client#308]
I started using the google-api-python-client in Google Cloud SDK, as the app-engine-python component, It appears they're using version `1.0beta7`. That's the version named in the setup.py in their `google-api-python-client` folder.
Is it possible to get them to update? If not, has anyone run into this before and have a workaround?

**Comment by jonparrott** [comment]
You'll have to file a bug on their public issuer tracker here: https://code.google.com/p/google-cloud-sdk/issues
