### ISSUE TITLE
Warning generated if MediaFileUpload ctor has extra arguments

### ISSUE THREAD

**Issue by griffin2000** [google/google-api-python-client#315]
MediaFileUpload ctor takes the optional parameters resumable and chunksize but if any of them are used a weird warning is generated.  It appears to do the right thing regardless of the warning, though.

E.g. this code:
```
from googleapiclient import discovery
from googleapiclient import http

from oauth2client.client import GoogleCredentials
source="e:/temp/clipboard.txt"
media = http.MediaFileUpload(source, 'application/octet-stream', resumable=True)
```
Will generate this warning (I guess an error that is being stomped?):
__init__() takes at most 2 positional arguments (3 given)

This is python 3.5.1 on Windows 8.1

**Comment by mcdonc** [comment]
This no longer appears to be the case with the master version of the API client.  I attempted to use MediaFileUpload with resumable=True and no warnings were produced.  Thanks for the report!
