### ISSUE TITLE
Youtube rate API does not increase like/dislike counter

### ISSUE THREAD

**Issue by kamii1000** [google/google-api-python-client#321]
I'm trying to like a video on user's behalf but got stuck in increment of like counter.
Like/Dislike counter is not updating. When a video is rated by api request, I get 200 response which means success according to docs. Also, video is available in user's Liked playlist and the like icon is blue on video but the like/dislike counter does not increase. I've waited for 2 days but the counter is still same. You can see the counter in picture attached.

![fireshot capture 12 - services - http___127 0 0 1_5001_services](https://cloud.githubusercontent.com/assets/13952928/21583698/52777518-d0ae-11e6-9fbc-e78757de7c37.png)

**Comment by kamii1000** [comment]
Unfortunately, there was no answer at that time. I don't know if there is any now.
And yes, I think you are right, this is a design decision by API team to stop spamming.

**Comment by mattwhisenhunt** [comment]
I'm going to close this issue. Give us a holler if you need anything else.

**Comment by aagarwal959** [comment]
Is it still pending. Or any solution found so far?
