### ISSUE TITLE
First call to GCP routes API hangs at times 

### ISSUE THREAD

**Issue by ramkumar-sankar** [google/google-api-python-client#331]
>> What steps will reproduce the problem?

Use a service account.
Boot up a fully loaded system with lot of configurations.
Setup GCP handle
Invoke a GCP API (e.g routes list) - the API hangs

http = httplib2.Http()
credentials = GoogleCredentials.get_application_default()
    if http:
        gcp = GCP_discovery.build('compute', 'v1', credentials=credentials, httt
p=http)
    else:
        gcp = GCP_discovery.build('compute', 'v1', credentials=credentials)
    list = gcp.routes().list(project = project).execute(http=http)

the last call to gcp never returns.  Replacing gcp.routes().list() with a different API also causes a hang.  If i restart the process everything goes through fine.

>> What is the expected output? What do you see instead?
Typically the API does not hang, but happens some times.
If i restart the process when it hangs, it works fine after that.

>> What is the output of 'gcloud info'?
Output shows properly - its the python API that hangs

>>> Please provide any additional information below.

Google Python API SDK version: 1.5.5
Python version: 2.7.6

Appreciate any insights into this issue.

Thanks

File: "/opt/avi/python/bin/cloud_connector/baremetal/gcp_client.py", line 677, in _reconcile_all_vips
  rtlist = gcp.routes().list(project=xpn_project).execute(http=http)
File: "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
  return wrapped(*args, **kwargs)
File: "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 833, in execute
  method=str(self.method), body=self.body, headers=self.headers)
File: "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 160, in _retry_request
  resp, content = http.request(uri, method, *args, **kwargs)
File: "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 175, in new_request
  redirections, connection_type)
File: "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 282, in request
  connection_type=connection_type)
File: "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
  (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File: "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
  (response, content) = self._conn_request(conn, request_uri, method, body, headers)
File: "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1334, in _conn_request
  content = response.read()
File: "/usr/lib/python2.7/httplib.py", line 578, in read
  return self._read_chunked(amt)
File: "/usr/lib/python2.7/httplib.py", line 620, in _read_chunked
  line = self.fp.readline(_MAXLINE + 1)
File: "/usr/lib/python2.7/socket.py", line 476, in readline
  data = self._sock.recv(self._rbufsize)
File: "/usr/lib/python2.7/ssl.py", line 341, in recv
  return self.read(buflen)
File: "/usr/lib/python2.7/ssl.py", line 260, in read
  return self._sslobj.read(len)

**Comment by jonparrott** [comment]
@ramkumar-sankar thanks for the bug report, there could be a hundred things causing this. We're adding a timeout in #320 that should mitigate this. Closing for now.
