### ISSUE TITLE
Accessing fit data using python api

### ISSUE THREAD

**Issue by sonus21** [google/google-api-python-client#332]
How can we access fit REST API using this client? I tried builder( "fit", "v1") but it fails.

 I tried using REST API but it didn't work as well, any plan to add fit v1 to this?

See http://stackoverflow.com/questions/41733466/accessing-google-fit-rest-api-using-python for error and question

**Comment by jonparrott** [comment]
I recommend giving feedback directly in the Fit application if you want access to that API.

We just maintain the client library, not the APIs themselves.

**Comment by sonus21** [comment]
So you meant developer has to write feedback in your fit android app ?????

**Comment by jonparrott** [comment]
Hmm, I may have misunderstood your request. We get a lot of bugs requesting a *new* API. I didn't realize we already have a fit API.

Looking at the [api explorer](https://developers.google.com/apis-explorer/#p/fitness/v1/) it seems you should do `googleapiclient.discovery.build('fitness', 'v1')`.

**Comment by sonus21** [comment]
You are right builder has to be build( 'fitness' , 'v1'),   how someone can use authentication token retrieved during authentication. I look at the drive example but it throws error invalid_grant (u'invalid_grant',). Can't find a way to solve this problem. You folks should consider updating a piece doc. If you want I can paste code here.

**Comment by jonparrott** [comment]
@sonus21 I'd recommend following these docs: https://developers.google.com/identity/protocols/OAuth2WebServer

**Comment by Yoanna16** [comment]
hey @sonus21 do you have a solution for the Google Fit Api, I am also struggling with finding a solution, always getting error messages

**Comment by Yoanna16** [comment]
Hey @sonus21 Thank you, this does not help, I found a solution myself, I just had to dig deeper in the methods of the requests. I will upload my solution the next days and post it here :) 
This helped a lot (thank you @theacodes) https://developers.google.com/identity/protocols/oauth2/web-server
the drive api and the google fit api are very different but very similar as well 
so for google drive would be: 
  files = drive.files().list().execute() 
and to get the heart rate data is like this: 
  files = drive.users().dataset().aggregate(userId='me', body=requestBody).execute()
