### ISSUE TITLE
Queries returns 'rows' as response instead of real data

### ISSUE THREAD

**Issue by voodoodror** [google/google-api-python-client#335]
Hi,

I have a python script that runs every 10 minute using latest google-api-python-client version (1.6.1).
I can't tell exactly when, but sometimes it just fails as it gets 'rows' as query result instead of real data (which should be just 1 row, USUALLY count query)

After checking with Google Cloud Platform Support and replicating the same problem from their side, it turns out that it's a bug in this API client as clarified by them (query included in message):

```
"---@compute:~/python-docs-samples/bigquery/api$ python getting_started.py MY-PROJECT-ID
Query Results:
Traceback (most recent call last):
  File "getting_started.py", line 75, in <module>
    main(args.project_id)
  File "getting_started.py", line 58, in main
    for row in query_response['rows']:
KeyError: 'rows'
```

On the other hand this issue is not reproducible using bq command line, the UI or the REST API. Also, looking carefully at the job ids, BigQuery is working as expected. There is no issue in our side. The 0 bytes processed in

```
SELECT table_id FROM serving.__TABLES__ WHERE LEFT(table_id,10) BETWEEN "2017_01_01" AND "2017_01_09"
```

it is expected too due to you are selecting the table_id and the query is not processing any data (instead, the second query process 15GB even when the error is returned)."

Waiting for your kind help,

Thanks!
Dror

**Comment by alvarogomezuria** [comment]
I'm adding more info:

I've replicated the issue using the [getting_started.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/api/getting_started.py).

To do that, I've executed the same query several times. The error seems to indicate that there isn't rows to show but this is not the case as the job succeeded. Looking internally at the job ID everything looks good.

 I did it using these queries:
 1 . `SELECT table_id FROM serving.__TABLES__ WHERE LEFT(table_id,10) BETWEEN "2017_01_01" AND "2017_01_09"`

2 . `SELECT COUNT(*) FROM serving.2017_01_16 WHERE timestamp BETWEEN TIMESTAMP("2017-01-16 07:00:00") AND TIMESTAMP("2017-01-16 07:59:59")`

What Dror is saying about the 0 bytes processed is that in the first query we are not processing any data, just getting the table_id (from the meta table). It's not relevant to the issue.

Also, I've got this error even when the query hit the cache.

Summarizing, for some unknown reason time to time the library is failing. After simple retry everything is working as expected. 

Sincerely,
Alvaro

**Comment by jonparrott** [comment]
> After simple retry everything is working as expected.

Interesting, so there's nothing that consistently reproduces this error?

**Comment by alvarogomezuria** [comment]
I'd say no. 
As I said before, I was able to reproduce it executing the same query several times (with a minute in between). However I'm currently trying to hit it again using a similar query [1] (I don't have access to customer dataset anymore) but I am not able to do it. Even if I do something "dirty" like [2], I'm getting the correct result [3] 60 times. 

[1] SELECT table_id FROM bigquery-public-data:noaa_gsod.__TABLES__ WHERE RIGHT(table_id,4) BETWEEN "1929" AND "1945"

[2] for ((n=0;n<60;n++)); do python getting_started.py my-project; done

[3] 
Query Results:
gsod1929
gsod1930
gsod1931
gsod1932
gsod1933
gsod1934
gsod1935
gsod1936
gsod1937
gsod1938
gsod1939
gsod1940
gsod1941
gsod1942
gsod1943
gsod1944
gsod1945

**Comment by jonparrott** [comment]
Is there anything this library should do? If not, can we close this?

**Comment by alvarogomezuria** [comment]
At this point, I don't know. 
The JOB ID at the moment of the failure looked good to me. And it wasn't possible to replicate it using the UI or bq command line.

We can close this. If Dror experiences this issue again, he can re-open it adding more info. Does it look good to you?

**Comment by jonparrott** [comment]
Thanks, @alvarogomezuria.
