### ISSUE TITLE
BatchHttpRequest stopped working

### ISSUE THREAD

**Issue by jakobholmelund** [google/google-api-python-client#336]
My service using BatchHttpRequest to call Prediction API 1.6 suddenly stopped working yesterday and can't seem to figure out what went wrong. It's been running nicely without a hickup for almost a year, i've updated the libraries every month with no problems. I can't really figure out who to blame, but i think you guys can at least help me out or point me in the right direction. The weird thing is that this stopped working a long time after i deployed so it could be that google changed something in their authentication flow that has trickled down to you guys..

I get suddenly get the following error

```
     batch.execute(http=http)
   File "/app/sonofatailorapp/oauth2client/_helpers.py", line 133, in positional_wrapper
     return wrapped(*args, **kwargs)
   File "/app/sonofatailorapp/googleapiclient/http.py", line 1420, in execute
     self._execute(http, self._order, self._requests)
   File "/app/sonofatailorapp/googleapiclient/http.py", line 1336, in _execute
     body = self._serialize_request(request)
   File "/app/sonofatailorapp/googleapiclient/http.py", line 1206, in _serialize_request
     request.http.request.credentials.apply(headers)
   File "/app/sonofatailorapp/oauth2client/client.py", line 563, in apply
     headers['Authorization'] = 'Bearer ' + self.access_token
 TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I've been playing around with google-api-python-client and oauth2client to try and get a better understanding of what is happening. while trying out stupid stuff i found that if added the following to transport.wrap_http_for_auth in oauth2client the error went away but something was still not working anyways as only 1 or 2 of the api calls gets through

```
def wrap_http_for_auth(credentials, http):
   credentials.get_access_token()
   ......
```

I'm writing here because you guys provide the api i'm using even though the mistake could be in oauth2lib.

My setup is like this

```
cridentials = service_account.ServiceAccountCredentials(
                settings.GOOGLE_PREDICTION_PROJECT_EMAIL, signer, scopes=[
                        'https://www.googleapis.com/auth/cloud-platform',
                        'https://www.googleapis.com/auth/devstorage.full_control',
                        'https://www.googleapis.com/auth/devstorage.read_only',
                        'https://www.googleapis.com/auth/devstorage.read_write',
                        'https://www.googleapis.com/auth/prediction',
                    ])
credentials = APIManager.get_cridentials()
http = httplib2.Http()
credentials.authorize(http)
service = build('prediction', 'v1.6')
batch = service.new_batch_http_request()
batch.add(trainedmodel, callback=prediction_callback)
batch.add(trainedmodel2, callback=prediction_callback2)
batch.add(trainedmodel3, callback=prediction_callback3)
batch.add(trainedmodel4, callback=prediction_callback4)
batch.add(trainedmodel5, callback=prediction_callback5)
batch.execute(http=http)
```

Please somebody help :)

**Comment by jonparrott** [comment]
@jakobholmelund 1.6.0 added support for the new google-auth library, can you try using that and see if it resolves your issue?

**Comment by jakobholmelund** [comment]
It worked !.. But i had to manually drop google_auth_httplib2.py in my project root and documentation is rather scarse.  

`$ pip install google-auth-httlib2`

Does not work

**Comment by jonparrott** [comment]
@jakobholmelund looks like there's a typo in the package description, should be `pip install google-auth-httplib2`.

Closing this issue.
