### ISSUE TITLE
Interest in synchronous call emulation against asynchronous APIs?

### ISSUE THREAD

**Issue by jbaublitz** [google/google-api-python-client#337]
I am interested in using this library instead of libcloud for a Google-specific project but have run into an issue with race conditions because of the implementation of the `.execute()` function for `HttpRequest`. There does not seem to be any way to emulate a synchronous call against an asynchronous API at the library level (poll the API in an `HttpRequest` instance function as opposed to in the calling code, and return only once the given action has completed in Google Cloud). For me, the lack of support for this out of the box is the only drawback I can see in using this library over libcloud.

Is this something that might be of interest to this project or is the caller of the library expected to handle and implement this functionality in an application-specific way each time? If so, could you explain the rationale for this?

**Comment by jonparrott** [comment]
> There does not seem to be any way to emulate a synchronous call against an asynchronous API

I'm not sure what you mean here. We don't have any "asynchronous" APIs as far as I know. We have APIs that return operations which you can later poll and get the status of.

> Is this something that might be of interest to this project

In general we're avoiding adding new features to this library unless there is a very strong case.

> libcloud

You might be interested in https://github.com/GoogleCloudPlatform/google-cloud-python if you're looking for a newer API client for Google Cloud Platform APIs.

**Comment by jbaublitz** [comment]
@jonparrott I'm sorry to post on a closed issue but this is related.

Just to clarify, I am not referring to asynchronous at the HTTP level. The Google APIs seem to be synchronous in terms of HTTP requests but the calls in `google-api-python-client` do indeed seem to be asynchronous as they do not wait for the cloud operation such as network creation to be completed.
