### ISSUE TITLE
The Travis instance for this repo needs to be upgraded

### ISSUE THREAD

**Issue by cclauss** [google/google-api-python-client#340]
The Travis instance has old versions of pip, Python 2, and Python 3.  It has no ability to test Python 3.5 and 3.6.  See https://github.com/google/google-api-python-client/pull/339

**Comment by jonparrott** [comment]
Travis doesn't so much need to be updated as much as we just need to tell travis to provide us with newer interpreters. See https://github.com/google/google-api-python-client/pull/341

**Comment by cclauss** [comment]
Well done!  Now I understand.
