### ISSUE TITLE
Deprecate https://code.google.com/p/google-api-python-client/ MOAR

### ISSUE THREAD

**Issue by dhermes** [google/google-api-python-client#35]
1. When Googling for `google-api-python-client` the [old project](https://code.google.com/p/google-api-python-client/) comes up before this one.
2. The massive amount of text on the front page makes the project still look active. Suggest nuking all text including and after
   > All following text is deprecated and left in only for historical purposes.
3. Remove the massive number of project members, downloads and Wiki.

If I am off-base, feel free to close this issue.

**Comment by bantini** [comment]
Closing this issue as it seems that the problems have been resolved. Feel free to reopen it if anything else comes up.
