### ISSUE TITLE
Printing rather than logging?

### ISSUE THREAD

**Issue by MaximilianR** [google/google-api-python-client#353]
It looks like the python client is printing in addition to logging, when querying from BigQuery? This makes controlling the output much harder, aside from being un-idiomatic.

Printing in white, logging in red:

![image](https://cloud.githubusercontent.com/assets/5635139/23176541/6028b884-f831-11e6-911a-48aa7741a4da.png)

**Comment by jonparrott** [comment]
@MaximilianR I think those prints are from the sample code. What code are you running?

**Comment by MaximilianR** [comment]
You're right, it's in pandas: https://github.com/pandas-dev/pandas/blob/master/pandas/io/gbq.py

Thanks for taking the time
