### ISSUE TITLE
Very very old samples. 

### ISSUE THREAD

**Issue by xxbinxx** [google/google-api-python-client#355]
I am having trouble working with these samples. Please upgrade or provide for newer django versions and for python3 as well if possible.

**Comment by dbrrt** [comment]
+1

**Comment by krabbypattified** [comment]
+1

**Comment by waprin** [comment]
Have you guys checked out [python-docs-samples ](https://github.com/googlecloudplatform/python-docs-samples)? It contains most of the up to date samples for Python on GCP. We could stand to be a bit more organized but I wanted to make sure you were aware of those repos.

**Comment by xxbinxx** [comment]
Will look into it,  thanks for the update. 
I think you should show a link to [python-docs-samples](https://github.com/googlecloudplatform/python-docs-samples) inside [google-api-python-client](https://github.com/google/google-api-python-client)
