### ISSUE TITLE
What's the config body for accelerator (GPU)?

### ISSUE THREAD

**Issue by naoko** [google/google-api-python-client#359]
I'm trying to attach "GPU". per [GCE Doc](https://cloud.google.com/compute/docs/gpus/add-gpus) I thought adding the following to the `body` might work but it doesn't seems to be.
```
'accelerator': {
            'type': accelerator_type,
            'count': accelerator_count
        },
```
Any advice would be appreciated.

Thank you

**Comment by jonparrott** [comment]
This is a much better question for stackoverflow, sorry! We don't maintain the API services, just this client.
