### ISSUE TITLE
API to accessing activity data?

### ISSUE THREAD

**Issue by ChillarAnand** [google/google-api-python-client#366]
There are few APIs exposed by google to check historical data [like](https://myactivity.google.com/delete?bulkdelete=1&bulkdelta=1489516199999999&log=all) [these](https://myactivity.google.com/myactivity). Can python client support this?

**Comment by lukesneeringer** [comment]
Does this exist in another language? We are not sure what exactly you are asking for.

**Comment by mcdonc** [comment]
It does not appear there is an API to get the data presented by https://myactivity.google.com/myactivity , apologies.
