### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by nekketsuuu** [google/google-api-python-client#367]
A link for WebTest in [README.md](https://github.com/google/google-api-python-client/blob/12751ca8bf2f72a6a4d240a0115b89308af6efe0/README.md) is broken.  According to [InternetArchive](http://web.archive.org/web/20160801000000*/http://pythonpaste.org/webtest/), it has redirected to [here](http://webtest.pythonpaste.org/en/latest/index.html).

How about changing the URI to [here](https://pypi.python.org/pypi/WebTest) or the destination of the redirect?

**Comment by lukesneeringer** [comment]
Hi @nekketsuuu We will check on this.

**Comment by andrewnester** [comment]
@nekketsuuu thanks for reporting the issue! @lukesneeringer @jonparrott I've just added PR fixing this.
