### ISSUE TITLE
ZeroDivisionError when calling 'MediaDownloadProgress.progress'

### ISSUE THREAD

**Issue by amamaenko** [google/google-api-python-client#369]
**Steps to Reproduce**

Have an empty Google Sheets file, and obtain it's id

Then the following code will fail with the ZeroDivisionError

```
   request = service.files().export_media(
            fileId=file_id,
            mimeType='text/csv')
    downloader = googleapiclient.http.MediaIoBaseDownload(out_stream, request)
    done = False
    while not done:
        status, done = downloader.next_chunk()
        print("Download %d%%." % int(status.progress() * 100))
```

**Explanation**
The reason is that empty file will return empty 'content-range' header. So in the `MediaIoBaseDownload.next_chunk()` the `self._total_size` will be set to 0.
Further down the line, the method `MediaDownloadProgress.progress' has these lines:

```
if self.total_size is not None:
      return float(self.resumable_progress) / float(self.total_size)
else:
      return 0.0
```

Note that `self.total_size is not None` returns `True` for self.total_size == 0

**Comment by lukesneeringer** [comment]
Thanks for reporting. We will look into this.

**Comment by andrewnester** [comment]
@amamaenko thanks for reporting! @lukesneeringer I just added PR fixing this issue.

**Comment by lukesneeringer** [comment]
Thanks @andrewnester!
