### ISSUE TITLE
Missing Content-Length and Content-Range from header

### ISSUE THREAD

**Issue by nibakai** [google/google-api-python-client#370]
I am using the Google Driver API python library to download file as CSV format.

google_drive_service = get_service()
mimeType = 'text/csv'
request = google_drive_service.files().export_media(fileId='abc', mimeType=mimeType)
fh = io.BytesIO()
downloader = MediaIoBaseDownload(fh, request)
done = False
while not done:
    status, done = downloader.next_chunk()
    print "Download %d%%." % int(status.progress() * 100)
fh.seek(0)
content = fh.getvalue()

Since it is a big tab, the downloading process breaks down by chunks. It keeps printing out "Downloading 0%". While the code is checking the download process, i looped through the library code. The reason why it show "Downloading 0%" all the time is because the http response does not have "content-range" and "content-length" headers, which cause the process check issue.

If you are interested in replicating this process. Create a spreadsheet and fill the cell values for columns 'A:E' and rows '1:10000'. Let me know if anyone had the same issue or have a clue about why this is happening. Here is the Gdrive code: https://github.com/google/google-api-python-client/blob/master/googleapiclient/http.py#L664-L691

**Comment by lukesneeringer** [comment]
```print "Download %d%%." % int(status.progress() * 100)```

Integer divison in Python 2 means this will always be 0. Use a float, and convert to int after you multiply by 100.
