### ISSUE TITLE
Logging client can't handle timestamp correctly

### ISSUE THREAD

**Issue by rkosegi** [google/google-api-python-client#371]
I'm trying to list log entries using this simple code (used [this](https://googlecloudplatform.github.io/google-cloud-python/stable/logging-usage.html) as reference):

```
from gcloud import logging as gcl                                                
if __name__ == '__main__':                                                       
    client = gcl.Client()                                                        
    logger = client.logger('log_checker')                                        
    filterStr = 'jsonPayload.ident="some-identifier"'                                
    for entry in client.list_entries(filter_=filterStr):                         
        print entry      
```                                                        
But it fails with following error:

> 
> Traceback (most recent call last):
>   File "3.py", line 12, in <module>
>     for entry in client.list_entries(filter_=filterStr):
>   File "/usr/lib/python2.7/site-packages/gcloud/logging/client.py", line 200, in list_entries
>     for resource in resources]
>   File "/usr/lib/python2.7/site-packages/gcloud/logging/client.py", line 153, in _entry_from_resource
>     return StructEntry.from_api_repr(resource, self, loggers)
>   File "/usr/lib/python2.7/site-packages/gcloud/logging/entries.py", line 115, in from_api_repr
>     timestamp = _rfc3339_nanos_to_datetime(timestamp)
>   File "/usr/lib/python2.7/site-packages/gcloud/_helpers.py", line 402, in _rfc3339_nanos_to_datetime
>     dt_str, _RFC3339_NANOS.pattern))
> ValueError: Timestamp: u'2017-03-20T11:34:58Z', does not match pattern: '\n    (?P<no_fraction>\n        \\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}  # YYYY-MM-DDTHH:MM:SS\n    )\n    \\.                                       # decimal point\n    (?P<nanos>\\d{1,9})                       # nanoseconds, maybe truncated\n    Z                                        # Zulu\n'
> 

Example log entry from gcloud console:

```
{
 insertId: "15mm8phg5caaiyf"   
 jsonPayload: {
  host: "abcd"    
  pid: "4841"    
  message: "Some message"    
  ident: "some-identifier"    
 }
 resource: {…}   
 timestamp: "2017-03-23T10:48:19Z"   
 labels: {…}   
 logName: "projects/abcd-123456/logs/abcd"   
}
```

How can I list log entries then?

**Comment by rkosegi** [comment]
It seems that nanos are required to be present, but my log entry has no such info in timestamp.
Could be nanos part in regexp optional?

**Comment by lukesneeringer** [comment]
Hi @rkosegi, thanks for reporting.
It looks like we are using a regex for parsing, and the API format has changed to include the time zone. We will look into this.

**Comment by forrestchang** [comment]
@lukesneeringer @rkosegi I want to fix this bug.

**Comment by forrestchang** [comment]
@lukesneeringer @rkosegi 

I have a question, because I don't use this module. So is gcloud module the same as googleapiclient?

**Comment by techieashish** [comment]
I will try and fix this bug

**Comment by mcdonc** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-python#5673
