### ISSUE TITLE
Android Browser Not Launching with OAuth 2.0

### ISSUE THREAD

**Issue by frankgould** [google/google-api-python-client#379]
Thanks for being here. I am finishing my Android app and was testing my startup authorization code when I found that the browser is not launching from my python code. It worked a few months ago but recently it stopped working. Below is the logcat saying it is launching the browser but it never appears.

I/python  ( 2947): Your browser has been opened to visit:
I/python  ( 2947):     https://accounts.google.com/o/oauth2/auth?scope=https[...]&access_type=offline
I/python  ( 2947): If your browser is on a different machine then exit and re-run this
I/python  ( 2947): application with the command-line parameter
I/python  ( 2947):   --noauth_local_webserver

I can manually launch the browser, Chrome in this instance, paste the [full] url from above, and it authenticates correctly. There are no error codes or message and it doesn't time out. I searched for anything relevant to this in Android but could not find any suggestions. This is Android 4.4.2.

**Comment by jonparrott** [comment]
I have no idea, the underlying library just uses the Python standard library `webbrowser` package. So if you upgraded python or moved to a new version of android it's possible that broke it.

**Comment by frankgould** [comment]
Thanks. I'll take a look over there. Haven't upgraded python or android versions. However, I probably did break something. ;-)

**Comment by tejastank** [comment]
@frankgould do you have any idea  on below issue?

Same issue: I run code in my localhost(worksfine) and live on VPS-Server(issue of --noauth_local_webserver).

with django use google analutics API.

In localhost working all fine, ask for google permission to access "google analytics" permission in automatically in browser new tab.

But same code I put on server it give me below message.

 

> Your browser has been opened to visit:
> 
>     https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=1071534795399-9q9urdlq845cu060e7isa56usjsdnu3o.apps.googleusercontent.com&access_type=offline
> 
> If your browser is on a different machine then exit and re-run this
> application with the command-line parameter
> 
>   --noauth_local_webserver

What should I had to do ?


  

>   parser = argparse.ArgumentParser('project-id-xxxx-xxxx --noauth_local_webserver',
>                     formatter_class=argparse.RawDescriptionHelpFormatter,
>                     parents=[tools.argparser],add_help=False)
>     flags = parser.parse_args([])
> 
>     flow = client.flow_from_clientsecrets('client_secret_1xxxxxxxx-xxx.apps.googleusercontent.com.json',
>                     scope='https://www.googleapis.com/auth/analytics.readonly',
>                     redirect_uri='urn:ietf:wg:oauth:2.0:oob')
> 
>     storage = file.Storage('analytics_%s'%request.user.id + '.dat')
>     credentials = storage.get()
>     if credentials is None or credentials.invalid:
>         credentials = tools.run_flow(flow, storage, flags)  


To short out issue on server, what should I had to do ??
