### ISSUE TITLE
HttpError 400 bad request in several apis

### ISSUE THREAD

**Issue by erictrinh276** [google/google-api-python-client#384]
I'm using this api library in Python 3 and can't call several methods like users.messages.send and users.labels.list.
The following is my code to get the list of labels:
```
SCOPES = ['https://www.googleapis.com/auth/gmail.labels']
CLIENT_SECRET_FILE = '/client_secret.json'
credentials = ServiceAccountCredentials.from_json_keyfile_name(CLIENT_SECRET_FILE, SCOPES)
http_auth = credentials.authorize(Http())
service = discovery.build('gmail', 'v1', http=http_auth)
labels = service.users().labels().list(userId='me')
```
this is labels in json:
`'{"method": "GET", "response_callbacks": [], "_in_error_state": false, "body": null, "methodId": "gmail.users.labels.list", "resumable_progress": 0, "body_size": 0, "resumable_uri": null, "uri": "https://www.googleapis.com/gmail/v1/users/me%40gmail.com/labels?alt=json", "headers": {"accept": "application/json", "accept-encoding": "gzip, deflate", "content-length": "0", "user-agent": "google-api-python-client/1.6.2 (gzip)"}, "resumable": null}'`

the credentials object  labels.http.request.credentials.to_json() (I stripped some personal information):
`'{"token_info_uri": null, "client_secret": null, "invalid": false, "token_uri": "https://accounts.google.com/o/oauth2/token", "_class": "ServiceAccountCredentials", "scopes": [], "token_response": {"expires_in": 3600, "token_type": "Bearer", "access_token": ""}, "_user_agent": null, "_private_key_pkcs8_pem": "-----BEGIN PRIVATE KEY----------END PRIVATE KEY-----\\n", "_service_account_email": "iam.gserviceaccount.com", "client_id": "", "id_token": null, "_scopes": "https://www.googleapis.com/auth/gmail.labels", "_private_key_id": "", "_module": "oauth2client.service_account", "revoke_uri": "https://accounts.google.com/o/oauth2/revoke", "access_token": "", "user_agent": null, "_kwargs": {}, "token_expiry": "2017-04-11T22:11:17Z", "assertion_type": null, "refresh_token": null}'`

when i call labels.execute(), i got:
```
Traceback (most recent call last):
  File "<pyshell#65>", line 1, in <module>
    message = (service.users().messages().send(userId = username, body = msg).execute())
  File "/usr/local/lib/python3.4/dist-packages/oauth2client-4.0.0-py3.4.egg/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/gmail/v1/users/me%40gmail.com/messages/send?alt=json returned "Bad Request">
```

**Comment by jonparrott** [comment]
@erictrinh276 The first obvious issue here is that gmail is a *user resource* API, which means you can't access it directly with a service account (you can use domain-wide delegation if you're using gSuite). You'll need to use the 3LO/User auth flow described here: https://developers.google.com/drive/v3/web/quickstart/python

**Comment by erictrinh276** [comment]
@jonparrott : But I'm authenticating and sending emails from my cron job running daily on my Raspberry Pi.I'm not sending emails on behalf of another user. I'm sending emails from my gmail account.
I use the Wizard to create the credential and it tells me to create a service account.
Options that I chose:
API: Gmail
Where: Other non UI
What data: Application data (belong to my application)
If I chose User data, it would show the warning: User data cannot be accessed from a platform without a UI because it requires user interaction for sign-in
Any thought?

**Comment by erictrinh276** [comment]
ahh my bad, it opens the browser so i can grant permission.
But what if my Pi OS doesn't have GUI?

**Comment by jonparrott** [comment]
@erictrinh276 you can do the initial authorization yourself to obtain an access token *and* refresh token. This refresh token can be used by the Pi to obtain new tokens without you present.

**Comment by erictrinh276** [comment]
Thank you for your clarification, @jonparrott
