### ISSUE TITLE
Documentation: No information on the data type returned by drive.files().export()

### ISSUE THREAD

**Issue by kpinc** [google/google-api-python-client#385]
I can't find any documentation on the data type returned by the drive.files().export() function for various mime types, or at all.  (E.g. Exporting a 'text/csv' seems to return bytearray, not str, despite the "text" in the mime type.)  Perhaps bytearray is returned regardless of mime type, if so this should be documented.  It's hard to use the API correctly without clarity as to the data type(s) returned.

Further, I can't find any documentation on what a google file resource returns for any given mime type.  What encoding is used, what RFC or other specification the content is expected to conform to, etc.  Without such information using the file resource is a matter of guesswork.  Since this second point is probably not client specific I'd appreciate assistance as to where to direct this latter issue.  Thank you.

**Comment by jonparrott** [comment]
@kpinc when retrieving files from the API, you'll always get back bytes representing that file regardless of mimetype. You can then save those bytes to disk, decode them to unicode if you know they're text, use ByteIO to treat it like an in-memory file, etc. 

I'm not sure on the second question, but in general it seems you're expecting the client/API to do more than just return the bytes for the file. Drive just fundamentally stores files (binary data) and metadata. When downloading or uploading, you are dealing with the binary data (the file in bytes) and any associated metadata (mime type, name, etc.).

**Comment by kpinc** [comment]
Thanks for the reply.

Where is it documented you always get bytes back from the API when you use python (or any other client)?  Specifically with respect to google-api-python-client, where does it say that the bytes you get come back as a particular python data type?  (Not that I want the answer here.  I want an answer in some documentation somewhere.  Are you saying that the API returns an immutable "bytes" class instance and not a mutable "bytearray" class instance?)

Regards the second question, I don't want the API to do anything.  If I make a file using the Google web interface and I use the Google API to request a particular mime type version of that file I want documentation on exactly what I'm going to get back.  I want documentation that says what specification Google says goes with each mime type.

**Comment by jonparrott** [comment]
@kpinc all of that seems to be documented here: https://developers.google.com/drive/v3/web/manage-downloads

**Comment by kpinc** [comment]
I'm sorry, I see nothing there close to what I'm asking for.  I see a list of mime types.  I see no information on what specification goes with each mime type.  If I ask for a text/csv spreadsheet am I going to get something separated by commas or semi-colons or one of the half dozen or so other common CSV file formats?  An RFC4180 CSV?  What is it's encoding?  Bytes are all well and good, but i need to convert to characters.  If I ask for a image/svg am I going to get back SVG 1.0, SVG 1.1, SVG 1.2, SVG Tiny, SVG Basic, or what?  Etc.

**Comment by jonparrott** [comment]
@kpinc that's a question better suited for stackoverflow, as we wouldn't know here and the API doesn't specify.
