### ISSUE TITLE
Django app cannot be started

### ISSUE THREAD

**Issue by seth4618** [google/google-api-python-client#387]
To get started I ran `python manage.py makemigrations` and get

    Traceback (most recent call last):
      File "manage.py", line 3, in <module>
        from django.core.management import execute_manager
    ImportError: cannot import name execute_manager

I am using django 1.10.1

**Comment by lukesneeringer** [comment]
Hi @seth4618,
Thanks for reporting. This is not an issue with the Google API client library, however, but either with Django itself or (more likely) your system setup. In particular, ensure that you are running that command from the virtualenv in which Django is installed.
