### ISSUE TITLE
ServerNotFoundError: Unable to find the server at www.googleapis.com

### ISSUE THREAD

**Issue by mikelambert** [google/google-api-python-client#388]
When inserting objects to Google Cloud Storage running from Flexible VMs on GCE, I often get this error:
```
ServerNotFoundError: Unable to find the server at www.googleapis.com
at _conn_request (/env/local/lib/python2.7/site-packages/httplib2/__init__.py:1278)
at _request (/env/local/lib/python2.7/site-packages/httplib2/__init__.py:1351)
at request (/env/local/lib/python2.7/site-packages/httplib2/__init__.py:1609)
at new_request (/env/local/lib/python2.7/site-packages/oauth2client/client.py:631)
at _retry_request (/env/local/lib/python2.7/site-packages/googleapiclient/http.py:154)
at execute (/env/local/lib/python2.7/site-packages/googleapiclient/http.py:827)
at positional_wrapper (/env/local/lib/python2.7/site-packages/oauth2client/util.py:135)
at put_object (/home/vmagent/app/util/gcs.py:48)
```

The code in question:
```
    req = service.objects().insert(
        bucket=bucket, body=body,
        # You can also just set media_body=filename, but for the sake of
        # demonstration, pass in the more generic file handle, which could
        # very well be a StringIO or similar.
        media_body=http.MediaIoBaseUpload(f, 'application/octet-stream'))
      resp = req.execute() # the line that throws the above exception
```

Any idea why a GCE Flexible VM would be unable to find the server `www.googleapis.com`?

**Comment by mikelambert** [comment]
And perhaps the question more related to this client library...is this something that might be fixed by switching to `google.cloud.storage` libraries versus these `googleapiclient` libraries?

**Comment by jonparrott** [comment]
Are you using a compat runtime?

**Comment by mikelambert** [comment]
Yes, I am using a derivation of the `python-compat` runtime. I've migrated over to `env: flex` at least, but am now slowly working through my dependencies to get off `python-compat` entirely.

**Comment by jonparrott** [comment]
> Yes, I am using a derivation of the python-compat runtime. 

That could be part of the problem. I'd see if you can do an isolated case without compat.

> is this something that might be fixed by switching to google.cloud.storage libraries versus these googleapiclient libraries?

Nah, they both hit the same endpoint.

**Comment by mikelambert** [comment]
> That could be part of the problem. I'd see if you can do an isolated case without compat.

Hahah dammit, I'm always scared the bitrot will bite me before I'm able to migrate off. The errors have recently increased in frequency in the past few days, and so I assumed it might be something on the other end.

Further investigation, the errors appear to be occurring on a single instance (not all instances), and start happening at some point, and continue until the service is repushed (or presumably, the instance restarts, but didn't test that yet.)

My best guess is there's some DNS/connectivity process running on the machine, that breaks down and causes problems. Can't find anything in my StackDriver logs that shows anything failing/breaking, though.

**Comment by karanpanchal-crest** [comment]
@mikelambert 
Is the problem of "Unable to find the server" issue is resolved in your environment?
If yes, can you please share the solution to the issue.
I am not able to figure out the reason behind the issue, The issue in my environment is as follows:
"Server is not responding to the client once or twice a week. On changing the Start time in my environment, the issue gets resolved."
**NOTE: "Start time" is a parameter used to collect data from the server starting from the given value.**

**Comment by mikelambert** [comment]
I am not sure exactly what I did to fix it. I do know that I currently create a new service each time I get/put an object. (In my case, I don't get/put them that often, so it is fine.) I suspect creating a new service anew with each request would probably help, but I understand that may not be a great solution for all use cases.

However, are you using the python-compat runtime too? ie app.yaml has `enable_app_engine_apis: true`?

**Comment by karanpanchal-crest** [comment]
Nope. Though I have built my product on the python language, I am not using python-compat runtime. But the issue occurs when my code tries to execute a connection request.

**Comment by mcdonc** [comment]
I don't think there's anything we can do on the client library side to help fix this.  It appears to be an intermittent connectivity issue between the host that is running the client library and the googleapis.com cluster.  I'm closing this as a result.  Even though this is nominally a "google problem" (as the code is running on GCE), there's not much from the perspective of the maintainers of this library we can do.
