### ISSUE TITLE
Put request examples?

### ISSUE THREAD

**Issue by justinsenseney** [google/google-api-python-client#391]
Are there any simple examples for doing put requests to the API using the Python client library?

**Comment by mattwhisenhunt** [comment]
https://developers.google.com/tasks/v1/reference/tasklists/update#examples

**Comment by mcdonc** [comment]
I may be missing something here, but the purpose of the client library is to abstract away the details of the HTTP operations from the developer.  The client library doesn't expose this level of control.  As a result, I am closing this issue.  If you believe I'm in error, please let me know.  Thanks!
