### ISSUE TITLE
Scope is not handled when using build() with http parameters

### ISSUE THREAD

**Issue by xcompass** [google/google-api-python-client#394]
According to the [docs](https://developers.google.com/identity/protocols/application-default-credentials#callingpython), When using build(), the scope is injecting automatically. However, it is not the case when using http parameters. It seems the scope handling is bypassed when http is specified. https://github.com/google/google-api-python-client/blob/master/googleapiclient/discovery.py#L358

Test code:
```bash
# use google default application credentials
export GOOGLE_APPLICATION_CREDENTIALS=/PATH/TO/GOOGLE_DEFAULT_CREDENTIALS.json
```
```python
import httplib2

from googleapiclient.discovery import build
from oauth2client.client import GoogleCredentials

credentials = GoogleCredentials.get_application_default()
#credentials = credentials.create_scoped('https://www.googleapis.com/auth/bigquery')

http = httplib2.Http()
http = credentials.authorize(http)

service = build('bigquery', 'v2', http=http)

jobs = service.jobs()
job_data = {'configuration': {'query': {'query': 'SELECT 1'}}}

jobs.insert(projectId='projectid', body=job_data).execute()
```
This will trigger the following error:
```
▶ python gbq_test.py
Traceback (most recent call last):
  File "gbq_test.py", line 17, in <module>
    jobs.insert(projectId='projectid', body=job_data).execute()
  File "/opt/python/pandas-gbq/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/python/pandas-gbq/lib/python2.7/site-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 401 when requesting https://www.googleapis.com/bigquery/v2/projects/ubcxdata/jobs?alt=json returned "Invalid Credentials">
```
 
If the create_scoped() is uncommented, the code executes correctly.

So when using the http parameter in build, is it expected that the scope is handled by http object already?

**Comment by jonparrott** [comment]
This is as intended, if you specify http then build doesn't nothing with credentials or the http itself. If you pass in http, it should already be authorized and setup. Otherwise, just pass credentials and let it construct the http itself. If you're using ADC, you can call build without http or credentials.

**Comment by xcompass** [comment]
Then maybe it should be mentioned in the docs :) I spent quite some time to figure this out.
