### ISSUE TITLE
Need authentication to run BigQuery query

### ISSUE THREAD

**Issue by yuri-wisestamp** [google/google-api-python-client#395]
Trying to execute a query from App Engine, in selfLink getting this response:
```
{
	error: {
		errors: [
		{
			domain: "global",
			reason: "required",
			message: "Login Required",
			locationType: "header",
			location: "Authorization"
		}],

		code: 401,
		message: "Login Required"
	}
}
```

I added the App Engine service account to the tables in the query - didn't help. How can I make the call from App Engine task to BigQuery without being blocked?

**Comment by mattwhisenhunt** [comment]
Are you still looking for a solution to this issue? In the time since you created it https://github.com/GoogleCloudPlatform/google-cloud-python has become the preferred client (for new code) for the BigQuery API.

I am here to help.

**Comment by JustinBeckwith** [comment]
Greetings!  If this is still an issue, please do let us know!
