### ISSUE TITLE
Error importing discovery from the client API

### ISSUE THREAD

**Issue by senthilmk** [google/google-api-python-client#404]
I am hitting the eror 

**"from oauth2client import util
ImportError: cannot import name util"** 

when I use the following imports:

**from googleapiclient import discovery
from oauth2client import client
from oauth2client import tools
from oauth2client.file import Storage**

Apparently this issue was fixed and closed, but I am seeing this in my IDE, so was not sure if this is deprecated and other ways to get this done. 

Thanks

**Comment by jonparrott** [comment]
What version of oauth2client and google-api-python-client do you have installed?

**Comment by senthilmk** [comment]
Using google-api-python-client 1.6.2 with oauth2client 4.1.1

**Comment by jonparrott** [comment]
Can you give the full stacktrace?

**Comment by senthilmk** [comment]
Traceback (most recent call last):
  File "**/gmail/gmail-sampler.py", line 5, in <module>
    from googleapiclient import discovery
  File "**/lib/python2.7/site-packages/googleapiclient/discovery.py", line 57, in <module>
    from googleapiclient.errors import HttpError
  File "**/lib/python2.7/site-packages/googleapiclient/errors.py", line 26, in <module>
    from oauth2client import util
ImportError: cannot import name util

**Comment by jonparrott** [comment]
So that's expected: https://github.com/google/google-api-python-client/blob/master/googleapiclient/errors.py#L28

I can't see why it wouldn't be catching that importerror and importing the >= v3 name.

**Comment by senthilmk** [comment]
and your suggestion to debug this would be??

**Comment by jonparrott** [comment]
I really sort of at a loss. Can you compare the file you have for `errors.py` with the one [here](https://github.com/google/google-api-python-client/blob/v1.6.2/googleapiclient/errors.py#L26)? The different in line numbers leads me to think that your app might somehow be picking up a different, older version.

**Comment by senthilmk** [comment]
Alrite. let me take a look and get back to you...Thanks
