### ISSUE TITLE
Documentation not correct for "import" function for variants

### ISSUE THREAD

**Issue by kkdang** [google/google-api-python-client#408]
Line 142 of google-api-python-client/googleapiclient/discovery.py
Reads:
_The name with a '\_' prefixed if the name is a reserved word._
Should read:
_The name with a '\_' appended if the name is a reserved word._

Also, the [suggested code in the docs](https://cloud.google.com/genomics/reference/rest/v1/variants/import)  for python is not correct about how to call this method.

The example line reading:
`request = service.variants().import(body=import_variants_request_body)
response = request.execute()`
Should be:
`request = service.variants().import_(body=import_variants_request_body)
response = request.execute()`

**Comment by mattwhisenhunt** [comment]
Fixed by #497
