### ISSUE TITLE
Question: gmail scope with step1_get_device_and_user_codes

### ISSUE THREAD

**Issue by fcaza** [google/google-api-python-client#41]
Hi,

It looks like we cannot use OAuth2WebServerFlow.step1_get_device_and_user_codes() with gmail service
It always return :
"OAuth2DeviceCodeError: Invalid response 400. Error: invalid_scope"
although I set different scope such as
'https://www.googleapis.com/auth/gmail.modify'
'https://www.googleapis.com/auth/gmail.compose'
'https://www.googleapis.com/auth/gmail.readonly'
'https://mail.google.com/'

oauth2_for_devices.py sample (https://github.com/google/oauth2client/blob/master/samples/oauth2_for_devices.py) works fine for 'youtube' or 'calendar' service, but not for gmail.
Did I miss something?

Thanks in advance for your feedback,
fcaza

**Comment by bantini** [comment]
oauth2client library is now deprecated. Hence, closing this issue.
