### ISSUE TITLE
translations().translate() incorrectly creates request body

### ISSUE THREAD

**Issue by jspalink** [google/google-api-python-client#418]
I'm attempting to use the services.translation().translate() call, but was running into problems with the request that is generated being formatted incorrectly.  I've solved the issue for myself with a subclassed HttpRequest that alters the body parameter.

```
from googleapiclient.discovery import build
from googleapiclient.http import HttpRequest
from googleapiclient.errors import HttpError

class myHttpRequest(HttpRequest):
    def __init__(self, http, postproc, uri, method=u'GET', body=None, headers=None, methodId=None, resumable=None):
        super(myHttpRequest, self).__init__(http, postproc, uri, method=method, body=body, headers=headers, methodId=methodId, resumable=resumable)
        self.headers[u'Referer'] = REFERER_DOMAIN_SPECIFIED_FOR_MY_KEY
        self.headers[u'User-Agent'] = MY_HTTPREQUEST_USER_AGENT

service = build(u'translate', u'v2', developerKey=MYKEY, requestBuilder=myHttpRequest)

x = service.translations().translate(body={'target':'en', 'q':[u'hola mundo', u'hallo welt']})
x.execute()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://translation.googleapis.com/language/translate/v2?alt=json&key=MYKEY returned "Missing required field target">
```

`x.body` is set to `{"data": {"q": ["hola mundo", "hallo welt"], "target": "en"}}`

My existing solution alters my subclassed HttpRequest to this:
```
class myHttpRequest(HttpRequest):
    def __init__(self, http, postproc, uri, method=u'GET', body=None, headers=None, methodId=None, resumable=None):
        if body and body.startswith('{"data": '):
            body = body[9:-1]
        super(myHttpRequest, self).__init__(http, postproc, uri, method=method, body=body, headers=headers, methodId=methodId, resumable=resumable)
        self.headers[u'Referer'] = REFERER_DOMAIN_SPECIFIED_FOR_MY_KEY
        self.headers[u'User-Agent'] = MY_HTTPREQUEST_USER_AGENT
```

What I'm doing here is simply getting rid of the surrounding `"data"` in the `x.body` string.  The `execute` method called elsewhere will then set the requests `body_size` and other headers appropriately.

Obviously, this is not a particularly elegant solution, but it solves the problem for me.  Am I using the HttpRequest incorrectly or doing something else wrong?  Is there a better way to use this call?  All of the examples of this library that I've found online seem to use the `list()` call rather than the `translate()` call.

**Comment by bantini** [comment]
@jspalink What if you use this instead?
```python
x = service.translations().list(
      source='es',
      target='en',
      q=[u'hola mundo', u'hallo welt']
    )
```

**Comment by bantini** [comment]
Closing this because there was no reply for over a week. Please reopen the issue if the problem persists.

**Comment by xirdneh** [comment]
For future references, this works:
`service.translations().list(
    source='es',
    target='en',
    q=[u'algo en español']
)`
For some reason `service.translations().translate()` does not.

**Comment by nonagonal** [comment]
> For future references, this works:
> 
> ```python
> service.translations().list(
>     source='es',
>     target='en',
>     q=[u'algo en español']
> )
> ```
> 
> For some reason `service.translations().translate()` does not.

Thanks! This worked for me too - it's unclear why list() performs translation successfully, but translate() seems to complain about "Missing required field target".
