### ISSUE TITLE
cut a release?

### ISSUE THREAD

**Issue by snarfed** [google/google-api-python-client#421]
hi all! first off, thanks for building and maintaining google-api-python-client. we appreciate it!

any chance you all could cut a new release sometime soon? the last one is almost 6 mos old now. i'm hoping to cut a new release of a library of my own (https://github.com/snarfed/granary) that depends on gapc, but it needs a bug fix (#350, #376) that hasn't been released yet.

thanks in advance!

**Comment by snarfed** [comment]
friendly nudge! without this, i'd need to switch my library to pip install google-api-python-client from github instead of pypi, which i'd really rather not do. :P

**Comment by snarfed** [comment]
hi! was closing this intentional? i'm not seeing a new release. (feel free to ignore me if you're working on it!)

**Comment by jonparrott** [comment]
Yep, a new release should be published.

**Comment by snarfed** [comment]
sorry, i'm probably missing something obvious, but i don't see the new release on either https://pypi.python.org/pypi/google-api-python-client or https://github.com/google/google-api-python-client/releases ...?

**Comment by jonparrott** [comment]
Oh no, I'm so sorry. I thought I had merged the PR and created the tag. It should be done now (https://github.com/google/google-api-python-client/releases/tag/v1.6.3) and it should upload to PyPI shortly.

**Comment by snarfed** [comment]
no worries! thank you!
