### ISSUE TITLE
HTTP Connection Pipelining Support

### ISSUE THREAD

**Issue by jof** [google/google-api-python-client#423]
Howdy Developers, I've got a quandary/question and wondering what is possible.

I'm developing an application for bulk uploading of large media files into Google Cloud Storage. However, my upload source is on the far end of a "long fat pipe" (high bandwidth, high latency). I am using this library's excellent support for simply writing objects into my bucket.

However, what I am finding is that I need to increase the concurrency of my upload workers to a very high amount in order to fully fill my bandwidth. Lots of time is wasted on many round-trips to establish connections.
In some manual testing of crafted upload requests, it seems that the API frontends support processing multiple requests through the same TLS/TCP/HTTP connection/transport. So, I'm trying to research how possible this would be using this library.
So far, I don't see any connection pooling logic or obvious ways to craft raw requests for use in other libraries.

There was some previous discussion in #218 about switching to using `google-auth` instead of `oauth2client`, which would enable the use of `requests` and `urllib3`'s connection pooling.
I'm starting to wonder if I will need to switch my project to craft multipart requests manually and wrap them with `google-auth`'s `google.auth.transport.requests.AuthorizedSession` requests wrapper.

Is there some other way to accomplish HTTP pipelining with this library?
Is there a better way to accomplish this?

**Comment by jonparrott** [comment]
You should look into using the newer [`google-cloud-storage`](https://github.com/googlecloudplatform/google-cloud-python) library. The next release will use `requests` as the http transport and will have connection pooling by default.

**Comment by jonparrott** [comment]
Oh - and the shorter answer - this library is inextricably tied to httplib2. There's no way we can support connection pooling and pipelining without breaking all of our users here. If you must use this library, I'd suggest checking out `httplib2shim`.

**Comment by jof** [comment]
Thank you for the lightning-quick reply @jonparrott 
`google-cloud-storage` looks a lot more like what I want!
Unfortunately, there doesn't seem to be clear pipelining support inside of `google-cloud-storage` either.

For future potential searchers, this is pretty verbose and feels a bit ugly, but here's an example of how I forced this to work for me:
```
#!/usr/bin/env python
from email.mime.multipart import MIMEMultipart
from email.mime.nonmultipart import MIMENonMultipart
try:
    from email.generator import BytesGenerator
except ImportError:
    from email.generator import Generator as BytesGenerator
import json
from six import BytesIO
import google.auth
from google.oauth2 import service_account
from google.auth.transport.requests import AuthorizedSession


class _BytesGenerator(BytesGenerator):
    _write_lines = BytesGenerator.write

def upload_blob(session, bucket, name, data):
    metadata = {
        "name": name
    }
    multipart_message = MIMEMultipart('related')
    setattr(multipart_message, '_write_headers', lambda self: None)
    metadata_message = MIMENonMultipart('application', 'json')
    metadata_message.set_charset('UTF-8')
    metadata_message.replace_header('Content-Transfer-Encoding', 'binary')
    metadata_message.set_payload(json.dumps(metadata), 'UTF-8')
    multipart_message.attach(metadata_message)
    content_message = MIMENonMultipart('application', 'octet-stream')
    content_message.add_header('Content-Transfer-Encoding', 'binary')
    content_message.set_payload(data)
    multipart_message.attach(content_message)
    fp = BytesIO()
    g = _BytesGenerator(fp, mangle_from_=False)
    g.flatten(multipart_message, unixfrom=False)
    body = fp.getvalue()
    multipart_boundary = multipart_message.get_boundary()
    headers = {}
    headers['Content-Type'] = ('multipart/related; boundary="%s"') % multipart_boundary
    headers['Content-Length'] = str(len(body))
    params = {}
    params['uploadType'] = 'multipart'
    upload_endpoint = "https://www.googleapis.com/upload/storage/v1/b/{bucket}/o"
    upload_endpoint = upload_endpoint.format(bucket=bucket)
    response = session.post(upload_endpoint,
                            params=params,
                            headers=headers,
                            data=body)

credentials, project = google.auth.default()
authed_session = AuthorizedSession(credentials)
bucket = "mybucket"
with open('/dev/urandom', 'r') as fh:
    fake_data1 = fh.read(1024)
    fake_data2 = fh.read(1024)

upload_blob(authed_session, bucket, "testing/fake_data1", fake_data1)
upload_blob(authed_session, bucket, "testing/fake_data2", fake_data2)
```

When I do this, I can confirm with wireshark that this only uses a single connection via urllib3's connection pooling.
