### ISSUE TITLE
people().connections().list() returns nothing

### ISSUE THREAD

**Issue by stevenmcastano** [google/google-api-python-client#429]
I have put the correct resource name in, as well as field masks. The call I'm making is:

```
service.people().connections().list( resourceName='people/me', pageSize=10, personFields='names,emailAddresses')
```

which returns nothing, but the same call in the same function to get me contact groups:

```
service.contactGroups().list()
```

returns exactly what I'd expect. Is anyone else seeing this behavior? Have I missed something?

**Comment by bantini** [comment]
@stevenmcastano Can you share the code that you were using?

**Comment by bantini** [comment]
Closing this issue because there was no response, so assuming that the user has found a solution. Feel free to reopen this issue if the problem persists.

**Comment by Offirmo** [comment]
See https://stackoverflow.com/questions/38680216/people-connections-list-not-returning-contacts-using-python-client-library
