### ISSUE TITLE
Get new access token from client after refresh

### ISSUE THREAD

**Issue by arivanandan** [google/google-api-python-client#430]
In "offline" mode when 

`credentials.authorize(httplib2.Http())`

is called, it refreshes the access_token. Is there any way to get this new access_token?

Pretty much the same as what's being talked about here: https://github.com/google/google-api-php-client/issues/901

**Comment by jonparrott** [comment]
You can get notified when a new token is obtained via https://oauth2client.readthedocs.io/en/latest/source/oauth2client.client.html#oauth2client.client.Storage

**Comment by arivanandan** [comment]
Thanks for your time.

client.Storage.get() expects the Storage object, I believe? I am not using one and I think the authorize function refreshes and stores the credentials in the http object passed to it.

**Comment by arivanandan** [comment]
I tried to create a store with 
`oauth2client.client.Storage`
but store.get() is not implemented yet?

Anyway, I ended up doing a refresh of the credentials outside and storing it
`
from oauth2client import client
credentials = client.OAuth2Credentials.from_json(self.credentials)
credentials.refresh(httplib2.Http())
auth = credentials.authorize(httplib2.Http())
self.credentials = credentials
`
