### ISSUE TITLE
Document which library replaces googleapiclient

### ISSUE THREAD

**Issue by NicolasLM** [google/google-api-python-client#436]
The README explains that this library is being deprecated, however it is not clear what is the recommended way to interact with non-GCP APIs.

**Comment by ender672** [comment]
It appears to be [google-auth-library-python](https://github.com/GoogleCloudPlatform/google-auth-library-python).

The python examples in the documentation for many google APIs still reference google-api-python client, so you will have to get familiar with google-auth-library-python.

**Comment by bantini** [comment]
[google-cloud-platform](https://github.com/GoogleCloudPlatform/google-cloud-python) will eventually be the one to use for all google services.
