### ISSUE TITLE
Deprecation of oauth2client dependency

### ISSUE THREAD

**Issue by snoepkast** [google/google-api-python-client#437]
According to the readme google/oauth2client is deprecated. They suggest switching to [google-auth](https://google-auth.readthedocs.io/) or [oauthlib](http://oauthlib.readthedocs.io/). 

This probably means that this package and all of the docs should also be refactored into using these new packages?

**Comment by linar-jether** [comment]
+1 
Any other usage docs for using `google-auth` or `oauthlib` with the api client libraries?

**Comment by xmedeko** [comment]
This lib still has a pip dependency to `oauth2client` and the code dependency, too, e.g. in the `errors.py`. Please, remove these dependencies and update the doc.

**Comment by amureki** [comment]
See comments here: https://github.com/google/google-api-python-client/issues/415

Seems like contributors are up for help with this one, if you have time and wish for it.
