### ISSUE TITLE
Report API did not return some field

### ISSUE THREAD

**Issue by starmood** [google/google-api-python-client#439]
Hi,

We are using Report API to get user's quota usage report.
But recently, we found from python client, the return result does not include some fields such as "accounts:gmail_used_quota_in_mb". 
I am not sure if it's Google API issue or python client issue. But when I use "APIs Explorer", it does return all fields, including "accounts:gmail_used_quota_in_mb"

**Comment by bantini** [comment]
@starmood Can you share the code that you are using?

**Comment by bantini** [comment]
Closing because there was no response, so assuming that the user has found a solution. Feel free to reopen the issue if the problem persists.
