### ISSUE TITLE
Get the error getsockaddrarg: AF_INET address must be tuple, not socket

### ISSUE THREAD

**Issue by suparnavg** [google/google-api-python-client#445]
Hello! Thanks for reading and thank you for your help in advance

I'm trying to implement the basic google calendar example here:  https://developers.google.com/api-client-library/python/start/get_started

Following the excellent instructions given, in an empty directory, I've created a new file and copied the code provided. I've also got a client ID and client secret from the Google API Console. When I start the server in the console, it starts successfully. However, on visiting localhost:8080, I get the following error:

**TypeError: getsockaddrarg: AF_INET address must be tuple, not socket.** 

The offending line of code (I think) is this one:
`server = HTTPServer(('', 8080), RequestHandler)`

Previously in the file, I've made a change to the RequestHandler function. As per the documentation, it should be:
`class RequestHandler(BaseHTTPServer.BaseHTTPRequestHandler):`

As this line was throwing errors, after some trial and error I changed it to the following and now those errors are gone:
`class RequestHandler(HTTPServer,BaseHTTPRequestHandler)`:

Any help would be much appreciated! Thank you! :+1:

**Comment by bantini** [comment]
@suparnavg What is the environment that you are working on (OS, Python version, etc.)

**Comment by suparnavg** [comment]
Hi @bantini I'm using Django 1.11 (should have mentioned it in the question itself!)

Not sure why this was happening, but I decided to park this approach altogether and try something else

**Comment by bantini** [comment]
Closing this issue since you have opted for a different approach. However, feel free to reopen it if you come across this again.

**Comment by ninjaspl0it** [comment]
Having the same issue

**Comment by ninjaspl0it** [comment]
Figured I would reply to this with how I solved this. By only including the "BaseHTTPRequestHandler" in my class all my troubles were gone somehow:

`    class CaptivePortal(BaseHTTPRequestHandler):`
`global httpd
    httpd = HTTPServer(('', PORT), CaptivePortal)`
