### ISSUE TITLE
PUBSUB_EMULATOR_HOST is Ignored

### ISSUE THREAD

**Issue by telenieko** [google/google-api-python-client#449]
Hi,

The [PubSub Emulator documentation](https://cloud.google.com/pubsub/docs/emulator) says:

> In all languages except for Java and C#, if you have set PUBSUB_EMULATOR_HOST as described in Setting environment variables, the Google Cloud Pub/Sub client libraries automatically call the API running in the local instance instead of the production API.

Note that there's no specification on what are the client libraries, so one could understand that any google sponsored libraries would work.

But that is not the case. This library (which is the best for consuming google services from Python btw) ignores the PUBSUB_EMULATOR_HOST variable.

Now, there is a specific PubSub client library for python but **most official code examples from Google** use apiclient, so newcomers end up trying to use the emulator with apiclient and find out it does not work.

Being specific, this GCP official sample: https://github.com/GoogleCloudPlatform/cloud-pubsub-samples-python/tree/master/appengine-push uses apiclient.

Possible fixes:

- Honour the PUBSUB_EMULATOR_HOST variable
- Accept an "endpoint" parameter to discovery.build (this would allow supporting any other emulators easily).

Thanks

**Comment by robhaswell** [comment]
Possibly related to https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3886

**Comment by robhaswell** [comment]
See: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3886#issuecomment-340488983

**Comment by bantini** [comment]
@telenieko Are you using the GoogleCloudPlatform library or this google-api-python-client?

**Comment by telenieko** [comment]
Hi @bantini ,

I use both, GoogleCloudPlatform has lots more dependencies than google-api-python-client so I try to use this one instead of the shiny new GoogleCloudPlatform. 

For this particular issue I brought it up on both sides ([see there](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3886#issuecomment-339246210)).

The other one is now fixed, but here the issue remains and being also an official google library it should honour such environment variables :)

**Comment by mcdonc** [comment]
Apologies, only the google-cloud-pubsub library will ever support this envvar; the google-api-python client library has no direct knowledge of pubsub; it simply translates discovery documents into a Python API.
