### ISSUE TITLE
Simplify Python Quickstart code

### ISSUE THREAD

**Issue by JoeCodeswell** [google/google-api-python-client#452]
The current Python Quickstart code contains:

    try:
        import argparse
        flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()
    except ImportError:
        flags = None

I don't see any use of it and it is taking up valuable "line realestate".

I suggest you delete this section.

Thanks.

Love and peace,
Joe Dorocak aka JoeCodeswell

**Comment by mattwhisenhunt** [comment]
Thanks for the heads up Joe. I have passed it along.
