### ISSUE TITLE
when i get access_toekn with code use client,i get ssl error

### ISSUE THREAD

**Issue by alaikis** [google/google-api-python-client#457]
requests.exceptions.SSLError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",),))

**Comment by alaikis** [comment]
![image](https://user-images.githubusercontent.com/30462479/33160409-12c17618-d057-11e7-8f2c-a8f99ebfba3f.png)

**Comment by bantini** [comment]
@alaikis Can you share the code for the implementation that is causing the problem?

**Comment by bantini** [comment]
Closing this because there was no response for over a week, so I am assuming the issue has been resolved. Feel free to reopen this if the issue persists.
