### ISSUE TITLE
This Library is now in maintenance- what its the accepted successor for google content api / shopping

### ISSUE THREAD

**Issue by Bobspadger** [google/google-api-python-client#463]
Quick question - is there a preferred library for using the Content/Shopping api in python if this is now no longer being worked on?

The link to google-cloud-python does not seem to make any reference to this API

Thanks :)

Alex

**Comment by bantini** [comment]
Please continue to use this library until [google-cloud-python](https://github.com/GoogleCloudPlatform/google-cloud-python) releases its version of the Content/Shopping API.
