### ISSUE TITLE
Please extends the API to retrieve downloads counts

### ISSUE THREAD

**Issue by sylvestre** [google/google-api-python-client#47]
We are using this API to publish APK to a many million users. It would be great if this API could be extended to return the number of downloads (per country, version, locale, ..)

**Comment by bantini** [comment]
As this library is in maintenance mode, we won't be adding any new features. However, please check the Play Console Help. The monthly reports might be of some help.

https://support.google.com/googleplay/android-developer/topic/3450942?hl=en
