### ISSUE TITLE
Add example of Sheet API v4

### ISSUE THREAD

**Issue by Barathwaja** [google/google-api-python-client#472]
Added the example of Sheets API with google-auth latest library, check PR #471 .

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. We have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
