### ISSUE TITLE
Developer metadata modules displays 404 - Sheets API

### ISSUE THREAD

**Issue by Barathwaja** [google/google-api-python-client#477]
The Developer Metadeta having sub links , all of them directs to 404 page.

for example, [creating developer metadata](https://developers.google.com/sheets/api/eap/reference/rest/v4/spreadsheets/request#createdevelopermetadatarequest).
How to create a metadata and tell the use of it clearly.

Thank you !!

**Comment by bantini** [comment]
@Barathwaja Thanks for bringing it up. Can you describe how you got to that page from the main documentation page?

**Comment by Barathwaja** [comment]
@bantini , the main documentation page is adding developer metadata, [click here for main url ](https://developers.google.com/sheets/api/guides/metadata#creating_new_metadata). In that page there are sub modules like create , update, delete , search .. If you click any of the hyperlinks say Reading Single metadata item in that click spreadsheet.metadata.get it redirects to 404 like that if you click any link under that page it goes to 404. So URLs are mapped wrongly in document

**Comment by Barathwaja** [comment]
Is this fixed or not??

**Comment by mattwhisenhunt** [comment]
Thanks for bringing this up. I have passed it along.
