### ISSUE TITLE
`googleapiclient.http.DEFAULT_CHUNK_SIZE` should be larger by default.

### ISSUE THREAD

**Issue by craigcitro** [google/google-api-python-client#481]
The default chunk size of 512kb is too small, and leads to slower-than-needed transfers, eg googlecolab/backend-container#1. 

Users can of course set the value larger as they'd like, but I suspect increasing it would lead to a better experience for users who don't know that there's a knob for them to twiddle.

**Comment by jonparrott** [comment]
Sounds reasonable. Send a PR?
