### ISSUE TITLE
Feature request: make it easier to cache a 3-legged auth credential

### ISSUE THREAD

**Issue by michaelsafyan** [google/google-api-python-client#483]
There is an API that requires a 3-legged auth flow like:

```python
def get_credentials_from_secrets(client_secrets_file, api_scope):
  flow = client.flow_from_clientsecrets(
      client_secrets_file,
      scope=api_scope,
      redirect_uri='urn:ietf:wg:oauth:2.0:oob')
  auth_uri = flow.step1_get_authorize_url()
  print 'Please navigate to:\n%s' % auth_uri
  auth_code = ''
  while not auth_code:
      auth_code = raw_input('Enter the auth code: ')
      auth_code = auth_code.strip()
  return flow.step2_exchange(auth_code)
```

When this is run in an interactive script like:

```python
#  ...
def main(args):
    creds = get_credentials_from_secrets(...)
    dispatch_by_command_and_execute(args, creds)
# ...
```

... this results in redundant authentication each time the script is run as in:

```bash
$ ./myapi.py list
$ ./myapi.py get --id=<id>
```

I'd really like a function like `get_credential_from_secrets` to be provided that automatically caches the credential. Bonus points for being smart about when to obtain the auth code via the terminal (such as when one is working in a headless environment such as SSHed remotely) vs via a browser. It doesn't make sense that multiple orgs and teams need to re-invent the wheel in implementing this caching.

**Comment by jonparrott** [comment]
The auth library used in your sample, `oauth2client`, is deprecated in favor of google-auth. Using 3LO with google-auth means using `oauthlib`/`requests-oauthlib` and there are lots of resources out there for dealing with storage for those libraries.

`oauth2client` does have `Storage` classes that can be used.

**Comment by michaelsafyan** [comment]
The documentation here:
https://developers.google.com/api-client-library/python/

Still references oauth2client. Can you ensure that the docs there are up-to-date?

**Comment by michaelsafyan** [comment]
Also note that documentation here:
https://developers.google.com/api-client-library/python/samples/samples

... likewise refrences "flow_from_clientsecrets".

**Comment by jonparrott** [comment]
Yes, I'm aware of this.
