### ISSUE TITLE
feature request - support of catalog api 

### ISSUE THREAD

**Issue by MrMichaelWill** [google/google-api-python-client#484]
https://cloud.google.com/billing/v1/how-tos/catalog-api is not currently in https://developers.google.com/api-client-library/python/apis/ 

I assume that means it is not implemented as a part of the google-api-python-client ? 

How hard would it be to implement it?

Is there a good code example in any of the existing implementations to learn how to do so?

**Comment by jonparrott** [comment]
The generated documentation isn't always up to date. This is showing up in the [api explorer](https://developers.google.com/apis-explorer/#search/cloudbilling.services.list/m/cloudbilling/v1/cloudbilling.services.list) so it should work here:

```python
cloudbilling = googleapiclient.discovery.build('cloudbilling', 'v1')
response = cloudbilling.services().list().execute()
```

**Comment by MrMichaelWill** [comment]
Not sure what you mean by not up to date. The cloud billing api is listed, I was talking about the catalog api instead, that would allow me to see prices for instances and services and such.

**Comment by MrMichaelWill** [comment]
Also your code snipped gets me

Traceback (most recent call last):
  File "test3b.py", line 5, in <module>
    response = cloudbilling.services().list().execute()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/http.py", line 844, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://cloudbilling.googleapis.com/v1/services?alt=json returned "Request contains an invalid argument.">


This is with:

import googleapiclient.discovery
cloudbilling = googleapiclient.discovery.build('cloudbilling', 'v1')
response = cloudbilling.services().list().execute()
print response

**Comment by jonparrott** [comment]
The "Catalog API" is just a sub-resource in the cloud billing API.

Looks like that API just needs an API key, so just be sure to pass one with the `developerKey` argument to `build`.

**Comment by MrMichaelWill** [comment]
Thank you Jon, appreciated.

I am wondering, since I can do the following for the compute api, can I do
something similar for the cloudbilling api as well?

compute = googleapiclient.discovery.build('compute', 'v1')

response = compute.zones().list(project='my-super-project').execute()


This works without me hardcoding or providing a key explicitely as a
parameter because of having issued a gcloud auth login saved the necessary
access credentials and/or tokens in ~/.config/gcloud/


Do I need to manage a separate key or is there a shorter path to use the
same authentication for the googleapiclient cloudbilling resource ?


Cheers, Michael Will



On Tue, Mar 13, 2018 at 1:40 PM, Jon Wayne Parrott <notifications@github.com

**Comment by jonparrott** [comment]
You can, it's just for some reason the cloud billing API doesn't expose its scopes, so you'll need to make sure the credentials have the cloud-platform scope:

```python
credentials, _ = google.auth.default(scopes=['https://www.googleapis.com/auth/cloud-platform'])

.. = googleapiclient.discovery.build('cloudbilling', 'v1', credentials=credentials)
```

**Comment by MrMichaelWill** [comment]
Fails already earlier:

import google

import googleapiclient.discovery

credentials, _ = google.auth.default(scopes=['
https://www.googleapis.com/auth/cloud-platform'])



Traceback (most recent call last):

  File "test4b.py", line 3, in <module>

    credentials, _ = google.auth.default(scopes=['
https://www.googleapis.com/auth/cloud-platform'])

AttributeError: 'module' object has no attribute 'auth'

On Tue, Mar 13, 2018 at 3:03 PM, Jon Wayne Parrott <notifications@github.com

**Comment by jonparrott** [comment]
You'll need to install google-auth and google-auth-httplib2.

**Comment by MrMichaelWill** [comment]
Done that, still not working:

import google
import google.auth
import googleapiclient.discovery

credentials, _ = google.auth.default(scopes=['https://www.googleapis.com/auth/cloud-platform'])
cloudbilling  = googleapiclient.discovery.build('cloudbilling', 'v1', credentials=credentials)

servicesList  = cloudbilling.services().list().execute()
print servicesList

Traceback (most recent call last):
  File "test3b.py", line 17, in <module>
    servicesList  = cloudbilling.services().list().execute()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/http.py", line 844, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://cloudbilling.googleapis.com/v1/services?alt=json returned "Request contains an invalid argument.">

I read that googleapiclient is in maintenance mode and I should just use google-cloud instead, but unfortunately that one does not support the catalog api either yet. 

So maybe I have to use the better documented rest interface with my own curl calls instead...
