### ISSUE TITLE
400 HTTP error when deleting google instance

### ISSUE THREAD

**Issue by akaars** [google/google-api-python-client#485]
Trying to delete google instance via googleAPI - the code which worked for me for the last year.
Now I receive the following error while trying to execute the _compute.instances().delete().execute()_:

`   File "/home/ilya/.local/lib/python2.7/site-packages/googleapiclient/http.py", line 844, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/compute/v1/projects/***?alt=json returned "The resource '*** is not ready">`

**Comment by jonparrott** [comment]
Hi @akaars, this does not appear to be an issue with this client library. I would recommend asking your question on Stackoverflow. The people who look after this repo do not typically have deep insights into server behavior.

**Comment by akaars** [comment]
You're absolutely right, my mistake, sorry for the disturbance.
The library behaves 100% as expected.
