### ISSUE TITLE
_retry_request not catching socket.timeout

### ISSUE THREAD

**Issue by thehesiod** [google/google-api-python-client#494]
the current retry logic says: `# Retry on SSL errors and socket timeout errors.`, and it catches socket.error looking for timeouts there, however timeouts in python are reported via `socket.timeout`

**Comment by thehesiod** [comment]
ok looks like the reason why is that socket.timeout is a subclass of socket.error however it's errno is None

**Comment by jonparrott** [comment]
Happy to accept a PR to add `socket.timeout` to the retry list [here](https://github.com/google/google-api-python-client/blob/master/googleapiclient/http.py#L173).

**Comment by thehesiod** [comment]
I'll extract a PR from my other uber PR that got closed ;)
