### ISSUE TITLE
Is asynchronous requests possible?

### ISSUE THREAD

**Issue by opensourcegeek** [google/google-api-python-client#50]
Is it possible to send asynchronous requests using this client library? I have few modules in app engine and I can run URL Fetch asynchronously to pull data from these modules concurrently, but there is an endpoint project and I'm not sure how to use this client library to run it asynchronously. Do I have to use some other mechanism or roll my own?

**Comment by xliiv** [comment]
+1

**Comment by wizravi** [comment]
Can anyone please answer this question

**Comment by jonparrott** [comment]
This library does have any provisions for making asynchronous requests.
