### ISSUE TITLE
How to use the client library with the new google-auth?

### ISSUE THREAD

**Issue by harel** [google/google-api-python-client#501]
Considering oauth2client is now deprecated, and does not work with Django 2.x, and that the recommended oauth library is google-auth, how does one use it with this client? It seems the docs are not updated to account for that and the client does not work with the new Credentials object. 
Any ideas?

**Comment by jonparrott** [comment]
This client work with google-auth automatically if it's installed. It accepts credentials objects from both oauth2client and google-auth and will continue to do so indefinitely.
