### ISSUE TITLE
client_secret.json vs client_secrets.json

### ISSUE THREAD

**Issue by charlesreid1** [google/google-api-python-client#506]
I've noticed a lot of inconsistency in example code given in various API documentation (I have looked at Calendar API, Directory API, Sheets API, YouTube API, and Drive API. I'm API-ed out). All of it uses this library, but some are using `client_secret.json` and others are using `client_secrets.json`. This repo seems to use `client_secrets.json` consistently so I don't understand why `client_secret.json` (no s) is being introduced.

But it *is* being introduced: see e.g. [this commit](https://github.com/youtube/api-samples/commit/6a4c3b283ce9e59e64e803173ddb5c35936b6e19) to the youtube api samples that changes `client_secrets.json` to `client_secret.json`. (Is this an official source of samples? a google person developing a side project? supported unofficially but officially? the chain of ownership here is left ambiguous and that's frustrating. their contributing document points to this repo.)

Meanwhile the [calendar sample](https://github.com/google/google-api-python-client/tree/master/samples/calendar_api) is hosted in this repo and uses `client_secrets.json` consistent with the rest of the repo.

In spite of all this, sometimes even the incorrectly-named file seems to work. What's going on here?

**Comment by mattwhisenhunt** [comment]
The name of the file is not important, its the content that counts. Depending on what language you are using and what environment your deploying to, you won't even have that json file.

https://github.com/youtube is an official source and it appears their api-samples repo is a helpful collection code samples to interact, specifically, with Youtube. I don't think those samples are limited to examples of this client library or its sister client libraries of other languages.

Google owns all the code, everyone agrees to that before their contribution is accepted: https://cla.developers.google.com/about/google-individual

I am sorry you are feeling frustrated and I've tried to answer your questions. If you have more specific problems or some code that is not working I would be glad help.

**Comment by charlesreid1** [comment]
Thanks for the explanation. Another cause of confusion was that the name of the json file is specified in [`sample_tools`](https://github.com/google/google-api-python-client/blob/master/googleapiclient/sample_tools.py) so it isn't clear where that comes from (or that it's arbitrary). The `sample_tools` import shows up in the samples like the [calendar sample](https://github.com/google/google-api-python-client/blob/master/samples/calendar_api/calendar_sample.py) but is also used in some documentation examples. 

Things started to click once I saw the [Drive API example](https://developers.google.com/drive/api/v3/quickstart/python) that explicitly goes through the whole process, where you specify yourself where the application's credentials live and where the Drive credentials will go. That made the 3-legged authentication process easier to see, and figure out why the Calendar API credentials were going in `calendar.dat` while Drive API credentials were going in `credentials.json`. 

Personally I don't think the magic is necessary, just my 2 cents.
