### ISSUE TITLE
get() expected a dict or protobuf message, got <class 'list'>. ERROR. HELP!

### ISSUE THREAD

**Issue by bionichuman** [google/google-api-python-client#509]
I keep getting this error and dont know how to fix it. 

get() expected a dict or protobuf message, got <class 'list'>.

I have all the auth I thought was needed.

**Comment by JustinBeckwith** [comment]
Thanks for the issue!  Can you please share:
- The code snippet that causes the error
- The complete stack trace when you get the error.

**Comment by mcdonc** [comment]
Closing due to lack of communication.  Please reopen if necessary.
