### ISSUE TITLE
Upload image to google drive

### ISSUE THREAD

**Issue by manikandan-enability** [google/google-api-python-client#517]
How to upload images from variable instead of uploading from directory?

For example 

imZ=cv2.imread('photo1.jpg')

In imZ the photo1.jpg image data will be available. Now I need to upload imZ as image in google drive instead of " MediaFileUpload('photo1.jpg',mimetype='image/jpeg') " .

**Comment by mcdonc** [comment]
@manikandan-enability  You need to use googleapiclient.http.MediaBaseIoBaseUpload; there is an example at https://google.github.io/google-api-python-client/docs/epy/googleapiclient.http.MediaIoBaseUpload-class.html
