### ISSUE TITLE
large file download fails with OverflowError

### ISSUE THREAD

**Issue by rupertlevene** [google/google-api-python-client#52]
On my 32-bit linux machine, files over 2GB fail to download. Memory usage gets very high while running the test script below, suggesting the entire download is being cached in memory. I think the download should be streamed to disk instead.

To use the script, upload a large file called bigvid.avi to google drive and put client_secrets.json in the working directory. 

This script uses PyDrive so I originally raised this issue at https://github.com/googledrive/PyDrive/issues/30 but aliafshar commented that the bug lies in google-api-python-client.

```
$ ./test.py 
bigvid.avi
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    f.GetContentFile('/tmp/bigvid-from-pydrive.avi')
  File "/usr/local/lib/python2.7/dist-packages/pydrive/files.py", line 167, in GetContentFile
    self.FetchContent(mimetype)
  File "/usr/local/lib/python2.7/dist-packages/pydrive/files.py", line 36, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pydrive/files.py", line 198, in FetchContent
    self.content = io.BytesIO(self._DownloadFromUrl(download_url))
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 54, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pydrive/files.py", line 313, in _DownloadFromUrl
    resp, content = self.auth.service._http.request(url)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 547, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1318, in _conn_request
    content = response.read()
  File "/usr/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 624, in _read_chunked
    return ''.join(value)
OverflowError: join() result is too long for a Python string
$ cat test.py
#!/usr/bin/env python

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

gauth=GoogleAuth()
if not gauth.LoadCredentialsFile("auth.txt") :
    gauth.CommandLineAuth()
    gauth.SaveCredentialsFile("auth.txt")

drive=GoogleDrive(gauth)

filelist=drive.ListFile({'q': "title='bigvid.avi'"}).GetList()
for f in filelist:
    print f['title'];
    f.GetContentFile('/tmp/bigvid-from-pydrive.avi')

$ ls -l /tmp/big*
ls: cannot access /tmp/big*: No such file or directory
```

**Comment by pferate** [comment]
Looking at the traceback, it looks like the error is coming from a combination of the built-in httplib trying to read the whole response (file) in a single string and the file being larger than the allowable string length on your system.  

It looks like at every level here (PyDrive, httplib2, httplib), each one is trying to store the content in a string, so you may continue to run into this while you are on a 32-bit system.  [More information here](http://stackoverflow.com/a/1739928/398514)

Sorry to keep pointing you to the "next castle", but it looks like the read() call is coming from [httplib2](https://github.com/jcgregorio/httplib2).  So the "chunking" could either be added to that library or you can add one yourself.

As a side note, in one of my side-projects, I was thinking of implementing a chunking download from Google Drive (for progress purposes), but it may additionally help stream it to a file.  If I ever get around to it, I'll try to feed it upstream.

**Comment by bantini** [comment]
Is anyone still facing these problems with the latest version of the library?

**Comment by mcdonc** [comment]
Triaging.

I'm afraid that this is a limitation of Python on 32-bit systems.

Python sequences on 32-bit systems (a string is a sequence, mulitple unicode characters defined with u'abc' is a sequence, etc. in Python) are limited to 2**31 entries.  As a result, strings in 32-bit Python are limited to 2GB.

On 64-bit systems, this limitation is removed (not really removed, but the resulting size limitation is absurd at the time of this writing, 2**63).

https://www.python.org/dev/peps/pep-0353/

I may try to set up a virtual environment with a 32-bit Linux distribution to see if there is some sort of workaround, but any change will be architectural, and not configuration.

**Comment by mcdonc** [comment]
No hand-rolling required to do progressive downloads.  Suggest to the PyDrive people that they use MediaIoBaseDownloader instead of trying to read the entire file into memory using the .get API.

```
import io

from oauth2client import file, client, tools
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload

store = file.Storage('credentials.json')
creds = store.get()
if not creds or creds.invalid:
    flow = client.flow_from_clientsecrets('client_secret.json', SCOPES)
    creds = tools.run_flow(flow, store)
service = build('drive', 'v3', http=creds.authorize(Http()))

files = service.files()
req = files.get_media(fileId=item['id'])
fh = io.FileIO('thing.deb', mode='wb')
req.uri = req.uri.replace('alt=json', 'alt=media')
downloader = MediaIoBaseDownload(fh, req, chunksize=1024*1024)
done = False
while done is False:
    status, done = downloader.next_chunk()
    if status:
        print("Download %d%%." % int(status.progress() * 100))
```

**Comment by mcdonc** [comment]
I'm going to close this issue, as it's actually in the hands of the PyDrive folks to implement something like I showed above.  If you need more help, though, please comment and I'll be happy to respond.
