### ISSUE TITLE
google-auth package conflicts with app engine library

### ISSUE THREAD

**Issue by idanya** [google/google-api-python-client#520]
Starting from version 1.7, the google-auth package is in use. 
This package using the namespace `google.*` which is the same as the app engine library. 

Imports we have used up until now like: `from google.appengine.ext import ndb`, now causing an ImportError because of the new google-auth package.

Is there a way to use 1.7 while working with app engine lib?

**Comment by theacodes** [comment]
HI there, are you using the instructions to do vendoring/copying? https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27

If so, this should just work - `google-auth` is tested against app engine standard.

**Comment by idanya** [comment]
I do use vendoring. `google-auth` creates a `google` directory inside "lib", then, when I import appengine components it tried to get them from this new directory instead of the app engine's one..

**Comment by idanya** [comment]
I am using `unittest`. Everything runs in a clean virtual environment after pip installing all deps with `pip install -r requirements.txt -t lib/`.
Setting `PYTHONPATH` to include appengine directory (`/usr/local/google_appengine` which is a sym link to the actual installation directory).

It all worked very well up until version 1.7.

**Comment by theacodes** [comment]
Setting PYTHONPATH is probably what's going wrong here. You'll need to do something like [this](https://github.com/GoogleCloudPlatform/python-repo-tools/blob/master/gcp_devrel/testing/appengine.py#L34-L36) to get it all playing nicely together.

Closing this for now, but happy to help if you need additional guidance.
