### ISSUE TITLE
Api Client to Create a New App

### ISSUE THREAD

**Issue by netmorais** [google/google-api-python-client#527]
Dear

I do not know if this is the proper channel for asking the question. I'm new to using the Google Play Console. Looking at the features of the Google Play Custom App Publishing API Client Library for Python I noticed that it is possible to "automate" several phases of Publishing.

All the examples I've known so far, using the Api Client, start with an App that was previously created using the Google Play Console. The question, while not knowing all the existing resources is:

Is there an Api Client, Python or other,  that can execute the Creation of a New App?

Thankful

**Comment by mattwhisenhunt** [comment]
Just scanning API Explorer briefly it looks to me like that API endpoint is
only for private/enterprise apps.

**Comment by JustinBeckwith** [comment]
Let's take a look in here, and see if it exists!
https://www.googleapis.com/discovery/v1/apis/

**Comment by mcdonc** [comment]
It appears there is a "create" method accessed via:

service.accounts().customApps().create(...)

See https://developers.google.com/resources/api-libraries/documentation/playcustomapp/v1/python/latest/playcustomapp_v1.accounts.customApps.html

I hope this helps.
