### ISSUE TITLE
RESTLESS vulnerability?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [google/google-api-python-client#534]
I couldn't find this in the issue tracker

https://www.danieldent.com/blog/restless-vulnerability-non-browser-cross-domain-http-request-attacks/

"Both the Python & Go SDKs provided by Google Cloud are vulnerable to variant 1 of this attack."

**Comment by mcdonc** [comment]
I suspect this may be a won't-fix, given the last paragraph of Daniel's blog entry.

**Comment by alexanderkjeldaas** [comment]
You mean this? "Google has declined to fix the above vulnerability through their security vulnerability reporting program. As of publication, no expected fix date is available."

I understand that it might not qualify for a vulnerability as it's not Google's data that will be compromised, but it's rather customers data stored outside of Google that can be attacked by Google.

Still, should be fixed, no?

**Comment by mcdonc** [comment]
FWIW, internal discussions amongst team members after I posted the above has not been unanimously in agreement with my take above.  I still believe that this is cause for minor concern, but I am only a collaborator.  I'm going to leave it up to Google folks to close or pursue this issue.

**Comment by alexanderkjeldaas** [comment]
> Is that how you interpret it too?

yes.  It's important that the client code treats the server as not trusted.  *Especially* when Google is the author on both sides.

**Comment by mcdonc** [comment]
I've (presumptously, sorry Thea) assigned @theacodes to this issue to make a call about what to do here.

**Comment by theacodes** [comment]
All of our APIs are accessed through HTTPS. If an attacker is able to compromise that we're already in endgame territory. Closing.

**Comment by alexanderkjeldaas** [comment]
HTTPS is out of scope for the threat described here.
