### ISSUE TITLE
Batch request for group members results in <BatchError "Invalid value for Content-ID: ...

### ISSUE THREAD

**Issue by chrish10e** [google/google-api-python-client#536]
Occurs in line 1191 of `http.py` - exact message is:

`googleapiclient.errors.BatchError: <BatchError "Invalid value for Content-ID: response- <cf4d6eb8-8f95-4fe1-ad82-2252fa9e8197+my-group@mydomain.com>">

If I insert `header = header.replace('response- ','')` at line 1175 the issue goes away.

**Comment by mcdonc** [comment]
Hi @chrish10e 

Do you think you can provide a bit of code that replicates this error for us?

**Comment by chrish10e** [comment]
Yes here you go:

`GROUPS_API = 'https://www.googleapis.com/auth/admin.directory.group.readonly'

# Create Service

store = file.Storage('my_store.json')
creds = store.get() 

if not creds or creds.invalid:
    flow = client.flow_from_clientsecrets('my_client_secrets.json', GROUPS_API)
    creds = tools.run_flow(flow, store)

service = build('admin', 'directory_v1', http=creds.authorize(Http()))

# Batch request members of groups

group_emails = ['groupemail1@mydomain.com', 'groupemail2@mydomain.com']

batch = service.new_batch_http_request()

for email in group_emails:
    batch.add(service.members().list(groupKey=email), request_id=email)

responses = batch.execute()

for response in responses:
    print('Got a response')`

**Comment by mcdonc** [comment]
Awaiting credentials from Google for GSuite so I can confirm the issue.

**Comment by rnovacek** [comment]
It happens to me too, I'm using this as a workaround:

```python
def fixed_header_to_id(self, header):
    # Workaround for https://github.com/google/google-api-python-client/issues/536
    header = header.replace('response- ', '')
    if header[0] != '<' or header[-1] != '>':
        raise BatchError("Invalid value for Content-ID: %s" % header)
    if '+' not in header:
        raise BatchError("Invalid value for Content-ID: %s" % header)
    base, id_ = header[1:-1].rsplit('+', 1)
    return unquote(id_)
```

```python
BatchHttpRequest._header_to_id = fixed_header_to_id
```

**Comment by mcdonc** [comment]
Assigned to @crwilcox at the behest of @JustinBeckwith

**Comment by mcdonc** [comment]
I just submitted a PR (https://github.com/google/google-api-python-client/pull/545) that should fix this.

**Comment by chrish10e** [comment]
I still get this error in `1.7..4`

**Comment by mcdonc** [comment]
@chrish10e indeed.. the next release will include the fix. Or you can use the master version from github.
