### ISSUE TITLE
Proxy doesn't work

### ISSUE THREAD

**Issue by kevinm90** [google/google-api-python-client#54]
When I try to execute this:
`
  credentials = client.SignedJwtAssertionCredentials(
      SERVICE_ACCOUNT_EMAIL,
      key,
      scope='https://www.googleapis.com/auth/androidpublisher')
  httplib2.debuglevel=4
  myproxy = httplib2.ProxyInfo(proxy_type = httplib2.socks.PROXY_TYPE_HTTP, proxy_host='http://proxy.my.comp', proxy_port=8080)
  myhttp = httplib2.Http(proxy_info=myproxy)
  authorization = credentials.authorize(myhttp)

  service = build('androidpublisher', 'v2', http=authorization)
`
I get this error:
httplib2.ServerNotFoundError: Unable to find the server at accounts.google.com

I also tried to set the proxy as env-variables. For basic stuff like installing via pip it works fine, but it doesn't work with the client. But I assume it should use the environment variables if nothing is set as proxy_info in the code.
Any suggestions on this?

Thanks!

**Comment by kevinm90** [comment]
Just wasnt aware that I have to add RDNS = true. (my company doesnot support DNS-Request to outside from the local machine so I have to force httplib2 to do the DNS-Request through the proxy and not from local)

**Comment by dmvieira** [comment]
Can you please share a code that solves it?

**Comment by dmvieira** [comment]
Here is working with environment variables:

`http_proxy=http://proxy_ip:proxy_port`

and

`https_proxy=http://proxy_ip:proxy_port`
