### ISSUE TITLE
Scope has changed

### ISSUE THREAD

**Issue by paulgholin** [google/google-api-python-client#551]
Hi there,
I ran the final complete example of https://developers.google.com/api-client-library/python/auth/web-app but encountered the following warning:

**builtins.Warning**
Warning: Scope has changed from "https://www.googleapis.com/auth/drive.metadata.readonly" to "https://www.googleapis.com/auth/plus.moments.write https://www.googleapis.com/auth/plus.profile.agerange.read https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/plus.circles.members.read https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/plus.profile.language.read".

I have no idea why it shows this warning; I can find "https://www.googleapis.com/auth/drive.metadata.readonly" in https://developers.google.com/identity/protocols/googlescopes. 

But it seems it's the following that is correct based on https://developers.google.com/identity/protocols/googlescopes
SCOPES = ['https://www.googleapis.com/auth/drive.metadata.readonly']
API_SERVICE_NAME = 'drive'
API_VERSION = 'v3'

instead of the following in your complete example:
SCOPES = ['https://www.googleapis.com/auth/drive.metadata.readonly']
API_SERVICE_NAME = 'drive'
API_VERSION = 'v2'

But the warning remains even after my change. 
Could you check this?
<img width="1248" alt="traceback" src="https://user-images.githubusercontent.com/6107838/43361528-8b2018d0-9285-11e8-8786-c883a4d0dea9.png">

Thank you.
Paul

**Comment by mcdonc** [comment]
I cannot replicate this.  Here is the output from my terminal when I run the flask application with my own credentials and hit the /test endpoint with my browser.  I authenticate successfully and see the API repsonse.

```
$ bin/python flaskapp.py 
 * Serving Flask app "flaskapp" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:8080/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 667-656-456
127.0.0.1 - - [31/Jul/2018 10:27:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2018 10:27:42] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [31/Jul/2018 10:27:48] "GET /test HTTP/1.1" 302 -
127.0.0.1 - - [31/Jul/2018 10:27:49] "GET /authorize HTTP/1.1" 302 -
127.0.0.1 - - [31/Jul/2018 10:27:59] "GET /oauth2callback?state=8jD6DeqxU6nimTEKmLEGSAfW3Rveof&code=4/AABUxE1GXHsDTL5meFFsvgQlOn83WwqQijzgUAdeDUwJcHC21fWlSBW3uFdfM-T-YlzCAYO3yjRZmajAg2Eu3H8&scope=https://www.googleapis.com/auth/drive.metadata.readonly HTTP/1.1" 302 -
127.0.0.1 - - [31/Jul/2018 10:28:01] "GET /test HTTP/1.1" 200 -
```

**Comment by mcdonc** [comment]
Here's a diagnosis from another project with a similar symptom:

https://github.com/gratipay/gratipay.com/issues/2862

**Comment by paulgholin** [comment]
It's pretty weird that there is no issue after I tried the same settings in a brand-new project...
