### ISSUE TITLE
Need up-to-date instructions for google-api-python-client on AppEngine.

### ISSUE THREAD

**Issue by milkypostman** [google/google-api-python-client#56]
Couple things I noticed in getting `google-api-python-client` to work on my AppEngine app,
1. https://developers.google.com/api-client-library/python/start/installation#appengine references a version of `google-api-python-client` that is old and uses the googlecode version of the code.
2. There are no updated instruction related to appengine on the github site.
3. The appengine demo in this repo doesn't immediately work.
4. It would be nice to have info about a process similar to http://blog.jonparrott.com/managing-vendored-packages-on-app-engine/ or a link to that post. But a duplication might be worthwhile.

**Comment by tmatsuo** [comment]
We updated the guide, so I think we can close this now.

**Comment by tmatsuo** [comment]
BTW thanks for the report @milkypostman

**Comment by milkypostman** [comment]
np, thanks for the update.

**Comment by bantini** [comment]
Closing this because the guide seems to be updated. Feel free to reopen the issue if anything comes up.
