### ISSUE TITLE
ImportError: cannot import name client

### ISSUE THREAD

**Issue by samiro** [google/google-api-python-client#59]
In sample: 
https://github.com/google/google-api-python-client/blob/master/samples/calendar_api/calendar_sample.py

I got error in line: 
```from oauth2client import client```

But i have installed:
* Soauth2client==1.4.6
* Sgoogle-api-python-client==1.3.1

**Comment by nathanielmanistaatgoogle** [comment]
What commands are you using to set up your Python environment and what command are you using to run the sample?

**Comment by samiro** [comment]
I'm sorry. I did have conflict with my Python environment.

It's working. Thanks.

**Comment by rodneykeeling** [comment]
@samiro Would you mind elaborating on what the conflict was? I'm having this same issue. Thank you!

**Comment by samiro** [comment]
Create a new virtual environment, and install libraries

**Comment by etanol** [comment]
For the record, we had the same issue with the same fix.  Executing `pip install google-api-python-client` did not correctly install the `oauth2client` nor `uritemplate` dependencies.  Moreover, no error was reported.

It appeared to be a result of a troublesome combination of `pip` and `setuptools` in our _virtualenv_.
