### ISSUE TITLE
Update instructions for apiclient on GAE.

### ISSUE THREAD

**Issue by craigcitro** [google/google-api-python-client#60]
Previously, we'd had custom instructions for setting up apiclient inside of a GAE project, and maintained scripts to build `zip` files as part of every release.

`pip` is sophisticated enough to handle this now, so we should update the instructions. this blog post is a good guide: 
  http://blog.jonparrott.com/managing-vendored-packages-on-app-engine/
(on that note -- thanks @jonparrott!)

this should address the issues in #49 and #56.

**Comment by jonparrott** [comment]
Note that [Darth](https://github.com/jonparrott/Darth-Vendor) is now part of the SDK under [google.appengine.ext.vendor](https://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/ext/vendor/__init__.py).

Let me know if I can do anything to help here.

**Comment by tmatsuo** [comment]
I think now we advertise to use pip everywhere. Is this still an issue?

**Comment by bantini** [comment]
Closing it as we have instructions to use pip with the libraries everywhere.
