### ISSUE TITLE
sendNotificationEmails is broken?

### ISSUE THREAD

**Issue by ghost** [google/google-api-python-client#65]
I am trying to change the ownership of some files from my service account to myself and it changes the ownership but I cannot for the life of me turn off the email notification. 

```
perm = {'value': 'me@example.com', 'type': 'user', 'role': 'owner'}
        service.permissions().insert(fileId=file_id, body=perm, sendNotificationEmails=False).execute()
```

Is this feature broken?

**Comment by bantini** [comment]
For anyone who comes back to this issue, this post might help:
https://stackoverflow.com/questions/29883085/how-do-i-turn-off-email-notifications-when-transferring-ownership
