### ISSUE TITLE
Humble Suggestion

### ISSUE THREAD

**Issue by timkofu** [google/google-api-python-client#69]
First of all, thank you for this library. 
I however have an idea on how to make it _much_ better though. If it had documentation like, for example, GAE (a comprehensive tutorial), that would make it _much_ more usable, maybe even increase Google revenue by 0.0001%

**Comment by dkkline** [comment]
Even just having samples, that work on Python 3 would be a big improvement, I think.

**Comment by bantini** [comment]
Closing this issue as the latest library is compatible with Python 3. Also, as this library is in maintenance mode, we are not adding any further tutorial on this. However, feel free to open an issue if you have any problem.
