### ISSUE TITLE
Copy doesn't interpret bucket name correctly

### ISSUE THREAD

**Issue by brandones** [google/google-api-python-client#72]
Looking at the URL being requested, it's clear that the bucket being requested is `foo-test`. However, for some reason, the server thinks I'm passing bucket name `foo-test/original`. It's wrong.

```
  File "/Users/bistenes/Code/MyOrg/product/env/lib/python2.7/site-packages/googleapiclient/http.py", line 723, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 400 when requesting https://www.googleapis.com/storage/v1/b/foo-test/o/original%2Fcopy.json/copyTo/b/foo-test/o/copy%2Fcopy.json?alt=json returned "Invalid bucket name: 'foo-test/original'.">
```

**Comment by brandones** [comment]
Ping.

**Comment by presveva** [comment]
ping

**Comment by nathanielmanistaatgoogle** [comment]
Might I trouble y'all for a more fleshed-out defect report? What library method are you calling, with what parameters, and what library behavior do you expect to see, and what library behavior do you observe?

http://www.chiark.greenend.org.uk/~sgtatham/bugs.html may be of even more help.

**Comment by bantini** [comment]
Anyone still facing the problem today? If so, can you share the code and the environment (OS, library version, etc.)?

**Comment by bantini** [comment]
Closing this issue assuming it has been resolved. Feel free to reopen it if the problem comes up again.
