### ISSUE TITLE
Documentation release process is broken

### ISSUE THREAD

**Issue by dkkline** [google/google-api-python-client#75]
Now that Python 3 support is (nearly) done, might I suggest that the next step would be updating the documentation regarding this project?

I've been struggling to get even a simple application up and running using this API, simply due to the lack of up-to-date, available documentation.

The documentation available at [developers.google.com](https://developers.google.com/api-client-library/python/) is not at all updated, and still advertises the use of `apiclient` instead of `googleapiclient`.

Furthermore, only cryptic, automatically-generated documentation is available at [google.github.io](https://google.github.io/google-api-python-client/).

I think it would be absolutely fantastic, if the documentation was improve, allowing developers to get into using this library more easily. I would love to help in any way I can, but sadly, I'm having a hard time gettings my bearings.

**Comment by nathanielmanistaatgoogle** [comment]
It looks like our `gh-pages` branch isn't getting updated as part of our release process and I'm not sure how api-python-client-doc.appspot.com fits into the story. Many things are not functioning correctly in terms of documentation for google-api-python-client, it seems.

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
