### ISSUE TITLE
Can't upload into beta track with higher versionCode than alpha

### ISSUE THREAD

**Issue by richardbrammer** [google/google-api-python-client#98]
When Uploading a new APK into beta track via the Publisher API, I get a 403 error, if there still is an APK in the alpa track, that has a lower android:versionCode.  

In my example I have an APK with version Code 49 in alpha. I modified my project, built a new APK and want to publish it as beta. Therefor I updated the versionCode to 50.

I can upload the APK 50 into the API edit, but as soon as I try and commit the changed, I receive the following error:

`<HttpError 403 when requesting https://www.googleapis.com/androidpublisher/v2/applications/[__bundleIdentifier__]/edits/474013840124732894710324789:commit?alt=json returned "Version 49 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.">`

If I publish the APK 49 to beta first, then I can overwrite it with the 50 successfully.

I wonder, if the observed behavior is by design? If so, I would argue, that it might not be close to practice: 
 1. I wouldn't expect any APK to move from alpha to beta without any changes and thus an update in the versionCode
 2. I would expect, that after leaving alpha base, some beta versions might follow, while not working on the alpha currently. 
 3. In the developer console, within the list of testers, it is mentioned, that an alpha tester will receive a beta APK, if no alpha APK is available. So updating the version code and changing the track to the beta seemed like a reasonable step.

**Comment by jaredsburrows** [comment]
I get this same error as well. I have published to `alpha` and I am trying to publish to `production`.

**Comment by spidfire** [comment]
your tracks always need to be like `production > beta > alpha` so the fast solution is to just clear the current alpha and beta before pushing to the production

**Comment by jonparrott** [comment]
Hi everyone, unfortunately you won't find a lot of help here as we only maintain the API client itself and we do not maintain the APIs. Your questions is probably better posed on Stackoverflow.

Thanks!
