### ISSUE TITLE
Error in converting googleapiclient.errors.HttpError to string

### ISSUE THREAD

**Issue by scribu** [google/google-api-python-client#99]
```python
try:
    results = ga.core.query.get()
except googleapiclient.errors.HttpError as err:
    print(err)  # TypeError: the JSON object must be str, not 'bytes'

    print(json.loads(err.content.decode('utf-8'))['error']['message'])  # works
```

Environment:

* Python 3.4.3
* google-api-python-client==1.4.0
* httplib2==0.9.1
* oauth2client==1.4.7
* six==1.9.0
* uritemplate==0.6

**Comment by Lance0312** [comment]
Looks like 0915761b fixed this issue. When is the next release coming out?

**Comment by scribu** [comment]
It looks like [1.4.1](https://github.com/google/google-api-python-client/releases/tag/v1.4.1) contains the fix.
